const exams = {
    exam1: [
        { question: "The shipment _____ at the warehouse yesterday.", options: ["arrive", "arrives", "arrived", "arriving"], answer: "arrived" },
        { question: "Please _____ the customer as soon as the goods arrive.", options: ["inform", "informs", "informed", "informing"], answer: "inform" },
        { question: "We _____ the documents to the customer two hours ago.", options: ["send", "have sent", "sent", "are sending"], answer: "sent" },
        { question: "The truck _____ at 8:00 tomorrow morning.", options: ["arrive", "arrived", "will arrive", "arriving"], answer: "will arrive" },
        { question: "There _____ three packages waiting at the warehouse.", options: ["is", "are", "was", "be"], answer: "are" },
        { question: "The goods have not arrived _____.", options: ["already", "yet", "still", "ever"], answer: "yet" },
        { question: "We need to check the invoice _____ sending it to the customer.", options: ["before", "during", "while", "until"], answer: "before" },
        { question: "The shipment was delayed _____ heavy rain.", options: ["because", "because of", "although", "despite"], answer: "because of" },
        { question: "Which word has the closest meaning to “shipment”?", options: ["employee", "delivery of goods", "warehouse", "invoice"], answer: "delivery of goods" },
        { question: "Which word means “hàng hóa”?", options: ["goods", "route", "carrier", "schedule"], answer: "goods" },
        // Phần 2 – Logistics Vocabulary
        { question: "A warehouse is a place where:", options: ["employees have meetings", "goods are stored", "trucks are repaired", "customers buy tickets"], answer: "goods are stored" },
        { question: "What does “delivery” mean?", options: ["Việc giao hàng", "Việc đóng gói", "Việc lưu kho", "Việc kiểm kê"], answer: "Việc giao hàng" },
        { question: "What is an invoice?", options: ["A document showing the details and cost of goods/services", "A truck used for transportation", "A place where goods are stored", "A shipping route"], answer: "A document showing the details and cost of goods/services" },
        { question: "A carrier is usually:", options: ["a company/person that transports goods", "a customer who buys goods", "a warehouse worker", "a type of invoice"], answer: "a company/person that transports goods" },
        { question: "If a shipment is delayed, it means:", options: ["It arrived earlier than expected.", "It arrived on time.", "It arrived later than expected.", "It was delivered to the wrong address."], answer: "It arrived later than expected." },
        { question: "Đọc đoạn email sau: <br/> Subject: Delivery Update <br/> Dear Mr. John, <br/> We would like to inform you that your shipment has been delayed due to bad weather. The truck was scheduled to arrive at our warehouse this morning, but it has not arrived yet. According to the carrier, the shipment is expected to arrive tomorrow afternoon. We apologize for the delay and will update you as soon as we receive further information.<br/> Best regards, <br/> Logistics Team ", options: ["a", "b", "c", "d"], answer: "d" },
        { question: "Why was the shipment delayed?", options: ["The truck broke down.", "The customer changed the address.", "Bad weather", "The warehouse was closed."], answer: "Bad weather" },
        { question: "When was the truck originally scheduled to arrive?", options: ["Yesterday afternoon", "This morning", "Tomorrow morning", "Tomorrow afternoon"], answer: "This morning" },
        { question: "When is the shipment expected to arrive?", options: ["This afternoon", "Tomorrow morning", "Tomorrow afternoon", "Next week"], answer: "Tomorrow afternoon" },
        { question: "Who sent the email?", options: ["The customer", "The carrier", "The warehouse manager", "The Logistics Team"], answer: "The Logistics Team" },
        { question: "What will the Logistics Team do?", options: ["Cancel the shipment", "Update the customer when they receive more information", "Send the shipment back", "Change the delivery address"], answer: "Update the customer when they receive more information" },
        { question: "A customer asks: 'Could you please tell me when my order will be delivered?' What is the best response?", options: ["I don't know", "Your order is expected to be delivered tomorrow.", "You should ask someone else.", "Why do you ask?"], answer: "Your order is expected to be delivered tomorrow." },
        { question: "Your customer says: 'I'm sorry, but I haven't received the shipment yet.' What is the most professional response? ", options: ["That's not my problem", "You must be wrong", "I'm sorry for the inconvenience. Let me check the shipment status for you.", "Wait"], answer: "I'm sorry for the inconvenience. Let me check the shipment status for you." },
        { question: "Your manager asks: 'Have you sent the invoice to the customer?' You have already sent it.", options: ["Yes, I have.", "Yes, I did tomorrow.", "Yes, I am.", "Yes, I send."], answer: "Yes, I have." },
        { question: "You didn't understand what your foreign customer said. What should you say?", options: ["What?", "Speak again.", "Could you please repeat that?", "I don't understand you."], answer: "Could you please repeat that?" },
        { question: "You need more time to check a customer's shipment. Which is the most professional?", options: ["Wait for me.", "Please give me a few minutes to check the shipment status", "I don't have time now", "Check it yourself."], answer: "Please give me a few minutes to check the shipment status" },
        { question: "Một khách hàng gửi email: 'We ordered 50 boxes, but only 45 boxes were delivered. Could you please check this issue?' Bạn nên hiểu rằng: ", options: ["Khách hàng nhận được 50 thùng nhưng muốn trả lại 45 thùng.", "Khách hàng đặt 45 thùng nhưng nhận 50 thùng.", "Khách hàng đặt 50 thùng nhưng chỉ nhận được 45 thùng.", "Khách hàng chưa nhận được bất kỳ thùng nào."], answer: "Khách hàng đặt 50 thùng nhưng chỉ nhận được 45 thùng." },
        { question: "Khách hàng hỏi: Can you confirm the estimated time of arrival? ETA trong logistics thường có nghĩa là:", options: ["Estimated Time of Arrival", "Estimated Transport Address", "Exact Time of Arrival", "Expected Transport Amount"], answer: "Estimated Time of Arrival" },
        { question: "Bạn nhận được thông báo: 'The shipment has been delivered to the wrong address.' Điều này có nghĩa là:", options: ["Hàng bị giao trễ.", "Hàng bị giao sai địa chỉ.", "Hàng bị mất.", "Hàng bị hư hỏng."], answer: "Hàng bị giao sai địa chỉ." },
        { question: "Khách hàng viết: 'Please provide us with the tracking number' Họ đang yêu cầu:", options: ["Số hóa đơn", "Số điện thoại tài xế", "Mã/số theo dõi đơn hang", "Địa chỉ kho"], answer: "Mã/số theo dõi đơn hang" },
        // { question: "", options: ["", "", "", ""], answer: "" },
    ],
    exam2: [
        { question: "Từ '请' nghĩa là gì?", options: ["Xin vui lòng", "Không", "Đúng", "Sai"], answer: "Xin vui lòng" },
        { question: "Từ '对不起' nghĩa là gì?", options: ["Xin lỗi", "Cảm ơn", "Xin chào", "Tạm biệt"], answer: "Xin lỗi" },
        { question: "Từ '早上好' nghĩa là gì?", options: ["Chào buổi sáng", "Chúc ngủ ngon", "Xin chào", "Tạm biệt"], answer: "Chào buổi sáng" }
    ]
};