const grammarList = [
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    { index: "1", name: "There is", mean: "There is = Có", example1: "Khẳng định: There is + Danh từ số ít / Danh từ không đếm được <br/> There is an apple on the table. (Có một quả táo trên bàn.) <br/> There is some water in the bottle. (Có một ít nước trong chai.)", example2: "Phủ định: There is not (isn't) + Danh từ <br/> There isn't any sugar left. (Không còn chút đường nào.) <br/>", example3: "Nghi vấn: Is there + Danh từ...? <br/> Is there a bank near here? (Có ngân hàng nào gần đây không?) <br/> Yes, there is. / No, there isn't."},
    { index: "2", name: "Phân biệt [There is] & [There are] & [Have]", mean: "", example1: "There is vs. There are: <br/> Dùng There is cho danh từ số ít hoặc không đếm được. <br/> Dùng There are cho danh từ số nhiều (There are three books on the desk).", example2: "There is vs Have: <br/> There is chỉ sự tồn tại khách quan (There is a car outside - Có một chiếc xe ở bên ngoài). <br/> Have/Has chỉ sự sở hữu của một chủ thể (I have a car - Tôi có/sở hữu một chiếc xe).", example3: "<br/> <br/>"},
    { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "1", name: "Dạng A不A (câu hỏi Khẳng định - Phủ định)", mean: "Trong tiếng Trung, có một dạng ngữ pháp đặc trưng để hỏi Yes/No: [Chủ ngữ] + [A不A câu hỏi] + [Động từ + Tân ngữ]", example1: "王先生要不要喝咖啡？ <br/> (Wáng xiānsheng yào bù yào hē kāfēi?) <br/> Ông Vương có muốn uống cà phê không?", example2: "這是不是烏龍茶？ <br/> (Zhè shì bú shì Wūlóng chá?) <br/> Đây có phải là trà Ô Long không?", example3: "臺灣人喜歡不喜歡喝茶？ <br/> (Táiwān rén xǐhuān bù xǐhuān hē chá?) <br/> Người Đài Loan có thích uống trà hay không?" },
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
];