const grammarList = [
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    { index: "1", name: "There is", mean: "There is = Có", example1: "Khẳng định: There is + Danh từ số ít / Danh từ không đếm được <br/> There is an apple on the table. (Có một quả táo trên bàn.) <br/> There is some water in the bottle. (Có một ít nước trong chai.)", example2: "Phủ định: There is not (isn't) + Danh từ <br/> There isn't any sugar left. (Không còn chút đường nào.) <br/>", example3: "Nghi vấn: Is there + Danh từ...? <br/> Is there a bank near here? (Có ngân hàng nào gần đây không?) <br/> Yes, there is. / No, there isn't."},
    { index: "2", name: "Phân biệt [There is] & [There are] & [Have]", mean: "", example1: "There is vs. There are: <br/> Dùng There is cho danh từ số ít hoặc không đếm được. <br/> Dùng There are cho danh từ số nhiều (There are three books on the desk).", example2: "There is vs Have: <br/> There is chỉ sự tồn tại khách quan (There is a car outside - Có một chiếc xe ở bên ngoài). <br/> Have/Has chỉ sự sở hữu của một chủ thể (I have a car - Tôi có/sở hữu một chiếc xe).", example3: "<br/> <br/>"},
    { index: "3", name: "Is he /she....?", mean: "Dạng câu hỏi: Is + he / she + [Danh từ / Tính từ / Cụm giới từ]? <br/> Cách trả lời: <br/> Đồng ý: Yes, he is. / Yes, she is. <br/> Không đồng ý: No, he isn't. / No, she isn't. (isn't = is not)", example1: "Hỏi về tên, danh tính hoặc nghề nghiệp (Đi với Danh từ): <br/> Is he a doctor? <br/> Yes, he is. / No, he isn't.", example2: "Hỏi về cảm xúc, tính cách, trạng thái hoặc ngoại hình (Đi với Tính từ): <br/> Is he happy today? <br/> No, he isn't. He is tired.", example3: "Hỏi về vị trí, địa điểm (Đi với Cụm giới từ chỉ nơi chốn): <br/> Is he at home? <br/> Yes, he is."},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    // { index: "", name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
];