
const personNameData = [
    //    { chinese: "", mean: "", pronunciation: "", pinyin: "" },
    { chinese: "開", mean: "mở; bật; mở ra", pronunciation: "khai", pinyin: "kāi" },
    { chinese: "文", mean: "chữ; văn tự; tiếng; ngôn ngữ", pronunciation: "quển", pinyin: "wén " },
    { chinese: "開文", mean: "Khai Văn", pronunciation: "khai quển", pinyin: "Kāi wén " },
    { chinese: "王", mean: "Vương (Vua)", pronunciation: "quảng", pinyin: "wáng " },
    { chinese: "阮", mean: "Họ Nguyễn", pronunciation: "Roản", pinyin: "ruǎn" },
    { chinese: "陳", mean: "Họ trần", pronunciation: "trấn", pinyin: "chén" },
    { chinese: "黎", mean: "Họ Lê", pronunciation: "lí", pinyin: "lí" },
    { chinese: "範", mean: "Họ Phạm", pronunciation: "Phan", pinyin: "fàn" },
    { chinese: "黃", mean: "Họ Hoàng", pronunciation: "Hoáng", pinyin: "huáng " },
    { chinese: "潘", mean: "Phan", pronunciation: "pan", pinyin: "pān" },
    { chinese: "明", mean: "Minh (làm rõ, sáng tỏ, hiểu biết)", pronunciation: "míng", pinyin: "míng" },
    { chinese: "英", mean: "Anh (nước Anh)", pronunciation: "ding", pinyin: "yīng" },
    { chinese: "輝", mean: "Huy (sáng sủa)", pronunciation: "huy", pinyin: "huī " },
    { chinese: "光", mean: "Quang (Ánh sáng)", pronunciation: "quang", pinyin: "guāng" },
    { chinese: "德", mean: "Đức (đạo đức)", pronunciation: "tửa", pinyin: "dé" },
    { chinese: "維", mean: "Duy (gìn giữ, bảo quản)", pronunciation: "quẩy", pinyin: "wéi" },
    { chinese: "香", mean: "Hương (mùi hương, hương thơm)", pronunciation: "xeng", pinyin: "xiāng" },
    { chinese: "玉", mean: "Ngọc (ngọc thạch, bảo thạch)", pronunciation: "duy", pinyin: "yù" },
    { chinese: "幸", mean: "Hạnh (hạnh phúc)", pronunciation: "xìng", pinyin: "xìng" },
    { chinese: "靈", mean: "Linh (Linh hồn)", pronunciation: "lỉng", pinyin: "líng" },
    { chinese: "莊", mean: "Trang (Thôn trang, trang viên)", pronunciation: "troang", pinyin: "zhuāng" },
    { chinese: "蘭", mean: "Lan (Hoa lan)", pronunciation: "lán", pinyin: "lán" },
    { chinese: "盛", mean: "Thịnh (Hưng Thịnh)", pronunciation: "shèng", pinyin: "shèng" },
    { chinese: "黎國盛", mean: "Lê Quốc Thịnh", pronunciation: "Líguóshèng", pinyin: "Líguóshèng" },
    { chinese: "張", mean: "Họ Trương (bày ra; trưng bày, khai trương)", pronunciation: "zhāng", pinyin: "zhāng" },
    { chinese: "怡", mean: "Di (vui vẻ; sung sướng; vui mừng; hân hoan)", pronunciation: "yí", pinyin: "yí" },
    { chinese: "君", mean: "Quân (vua; quân chủ; quân vương)", pronunciation: "jūn", pinyin: "jūn" },
    { chinese: "張怡君", mean: "Trương Di Quân", pronunciation: "Zhāngyíjūn ", pinyin: "Zhāngyíjūn" },
    { chinese: "安", mean: "An (an toàn; bình an; bình yên)", pronunciation: "ān", pinyin: "ān" },
    { chinese: "同", mean: "Đồng (cùng; giống nhau; tương đồng; như nhau)", pronunciation: "tóng", pinyin: "tóng" },
    { chinese: "馬安同", mean: "Mã An Đồng", pronunciation: "Mǎ ān tóng", pinyin: "Mǎ ān tóng" },
    { chinese: "田", mean: "Ruộng, họ Điền [field, surname Tián]", pronunciation: "tián", pinyin: "tián" },
    { chinese: "中", mean: "Ở giữa, trung [middle, center]", pronunciation: "zhōng", pinyin: "zhōng" },
    { chinese: "誠", mean: "Thành thật, chân thành [honest, sincere]", pronunciation: "chéng", pinyin: "chéng" },
    { chinese: "田中誠一", mean: "điền trung thành nhất", pronunciation: "Tián Zhōng Chéng Yī", pinyin: "Tián Zhōng Chéng Yī" },
    { chinese: "如", mean: "Như, giống như", pronunciation: "rú", pinyin: "rú" },
    { chinese: "白如玉", mean: "Bạch Như Ngọc; tên riêng", pronunciation: "bái rú yù", pinyin: "bái rú yù" },
];