const radicalList = [
    { chinese: "人 (亻)", mean: "người", sino_vietnamese: "nhân", pinyin: "rén", pronunciation: "rấn" },
    { chinese: "刀 (刂)", mean: "dao", sino_vietnamese: "đao", pinyin: "dāo", pronunciation: "tao" },
    { chinese: "力", mean: "sức mạnh", sino_vietnamese: "lực", pinyin: "lì", pronunciation: "lị" },
    { chinese: "口", mean: "miệng", sino_vietnamese: "khẩu", pinyin: "kǒu", pronunciation: "khẩu" },
    { chinese: "囗", mean: "vây quanh", sino_vietnamese: "vi", pinyin: "wéi", pronunciation: "uây" },
    { chinese: "土", mean: "đất", sino_vietnamese: "thổ", pinyin: "tǔ", pronunciation: "thủ" },
    { chinese: "大", mean: "To lớn", sino_vietnamese: "đại", pinyin: "dà", pronunciation: "ta" },
    { chinese: "女", mean: "nữ", sino_vietnamese: "nữ", pinyin: "nǚ", pronunciation: "nủy" },
    { chinese: "宀", mean: "máy nhà", sino_vietnamese: "miên", pinyin: "mián", pronunciation: "miền" },
    { chinese: "山", mean: "núi", sino_vietnamese: "sơn", pinyin: "shān", pronunciation: "san" },
    { chinese: "巾", mean: "khăn", sino_vietnamese: "cân", pinyin: "jīn", pronunciation: "chin" },
    { chinese: "广", mean: "máy nhà", sino_vietnamese: "nghiễm", pinyin: "guǎng", pronunciation: "quảng" },
    { chinese: "彳", mean: "bước chân", sino_vietnamese: "xích", pinyin: "chì", pronunciation: "chừ" },
    { chinese: "心 (忄)", mean: "tim", sino_vietnamese: "tâm", pinyin: "xīn", pronunciation: "xin" },
    { chinese: "手 (扌)", mean: "tay", sino_vietnamese: "thủ", pinyin: "shǒu", pronunciation: "sẩu" },
    { chinese: "攴 (攵)", mean: "đánh", sino_vietnamese: "phộc", pinyin: "pū", pronunciation: "pu" },
    { chinese: "日", mean: "mặt trời", sino_vietnamese: "nhật", pinyin: "rì", pronunciation: "rư" },
    { chinese: "木", mean: "cây", sino_vietnamese: "mộc", pinyin: "mù", pronunciation: "mù" },
    { chinese: "水 (氵)", mean: "nước", sino_vietnamese: "thủy", pinyin: "shuǐ", pronunciation: "suẩy" },
    { chinese: "火 (灬)", mean: "lửa", sino_vietnamese: "hỏa", pinyin: "huǒ", pronunciation: "hủa" },
    { chinese: "牛", mean: "trâu", sino_vietnamese: "ngưu", pinyin: "niú", pronunciation: "níu" },
    { chinese: "犬 (犭)", mean: "chó", sino_vietnamese: "khuyển", pinyin: "quǎn", pronunciation: "chuyển" },
    { chinese: "玉", mean: "ngọc", sino_vietnamese: "ngọc", pinyin: "yù", pronunciation: "duy" },
    { chinese: "田", mean: "ruộng", sino_vietnamese: "điền", pinyin: "tián", pronunciation: "thiển" },
    { chinese: "疒", mean: "bệnh", sino_vietnamese: "nạch", pinyin: "nì", pronunciation: "nơ" },
    { chinese: "目", mean: "mắt", sino_vietnamese: "mục", pinyin: "mù", pronunciation: "mu" },
    { chinese: "石", mean: "đá", sino_vietnamese: "thạch", pinyin: "shí", pronunciation: "sỉ" },
    { chinese: "禾", mean: "lúa", sino_vietnamese: "hòa", pinyin: "hé", pronunciation: "Khửa" },
    { chinese: "竹", mean: "tre", sino_vietnamese: "trúc", pinyin: "zhú", pronunciation: "chú" },
    { chinese: "米", mean: "gạo", sino_vietnamese: "mễ", pinyin: "mǐ", pronunciation: "mỉ" },
    { chinese: "糸 (纟)", mean: "tơ", sino_vietnamese: "mịch", pinyin: "mì", pronunciation: "mì" },
    { chinese: "肉 (月)", mean: "thịt", sino_vietnamese: "nhục", pinyin: "ròu", pronunciation: "rou -> rẩu" },
    { chinese: "艸 (艹)", mean: "cỏ", sino_vietnamese: "thảo", pinyin: "cǎo", pronunciation: "thảo" },
    { chinese: "虫", mean: "côn trùng", sino_vietnamese: "trùng", pinyin: "chóng", pronunciation: "chủng" },
    { chinese: "衣 (衤)", mean: "áo", sino_vietnamese: "y", pinyin: "yī", pronunciation: "i" },
    { chinese: "言 (讠)", mean: "lời nói", sino_vietnamese: "ngôn", pinyin: "yán", pronunciation: "dẻn" },
    { chinese: "貝 (giản thể 贝)", mean: "vỏ sò", sino_vietnamese: "bối", pinyin: "bèi", pronunciation: "bây" },
    { chinese: "足", mean: "chân", sino_vietnamese: "túc", pinyin: "zú", pronunciation: "chú" },
    { chinese: "車", mean: "xe", sino_vietnamese: "xa", pinyin: "chē", pronunciation: "trưa" },
    { chinese: "辶", mean: "bước", sino_vietnamese: "sước", pinyin: "chuò", pronunciation: "chua" },
    { chinese: "邑 (阝-phải)", mean: "làng", sino_vietnamese: "ấp", pinyin: "yì", pronunciation: "ị" },
    { chinese: "金", mean: "kim loại", sino_vietnamese: "kim", pinyin: "jīn", pronunciation: "chin" },
    { chinese: "門", mean: "cửa", sino_vietnamese: "môn", pinyin: "mén", pronunciation: "mển" },
    { chinese: "阜 (阝-trái)", mean: "đất cao", sino_vietnamese: "phụ", pinyin: "fù", pronunciation: "phu" },
    { chinese: "雨", mean: "mưa", sino_vietnamese: "vũ", pinyin: "yǔ", pronunciation: "dũy" },
    { chinese: "頁", mean: "đầu", sino_vietnamese: "hiệt", pinyin: "yè", pronunciation: "dia" },
    { chinese: "食", mean: "ăn", sino_vietnamese: "thực", pinyin: "shí", pronunciation: "sỉ" },
    { chinese: "馬", mean: "ngựa", sino_vietnamese: "mã", pinyin: "mǎ", pronunciation: "mã" },
    { chinese: "魚", mean: "cá", sino_vietnamese: "ngư", pinyin: "yú", pronunciation: "dũy" },
    { chinese: "鳥", mean: "chim", sino_vietnamese: "điểu", pinyin: "niǎo", pronunciation: "niểu" },
    { chinese: "冖", mean: "trùm, che", pronunciation: "mì", pinyin: "mì", sino_vietnamese: "mịch" },
    { chinese: "冫", mean: "băng, lạnh", pronunciation: "bing", pinyin: "bīng", sino_vietnamese: "băng" },
    { chinese: "又", mean: "lại, lần nửa", pronunciation: "dâu", pinyin: "yòu", sino_vietnamese: "hựu" },
    { chinese: "夕", mean: "buổi tối", pronunciation: "xi", pinyin: "xī", sino_vietnamese: "tịch" },
    { chinese: "子", mean: "con trai", pronunciation: "dư", pinyin: "zǐ", sino_vietnamese: "tử" },
    { chinese: "小", mean: "nhỏ, bé", pronunciation: "xiểu", pinyin: "xiǎo", sino_vietnamese: "tiểu" },
    { chinese: "尸", mean: "xác chết, thể xác", pronunciation: "si", pinyin: "shī", sino_vietnamese: "thi" },
    { chinese: "工", mean: "công việc, thợ, thủ công", pronunciation: "cung", pinyin: "gōng", sino_vietnamese: "công" },
    { chinese: "干", mean: "cái khiên, che, Khô, can dự", pronunciation: "cang", pinyin: "gān", sino_vietnamese: "can" },
    { chinese: "幺", mean: "út, bé nhỏ, thứ yếu", pronunciation: "dao", pinyin: "yāo", sino_vietnamese: "yêu" },
    { chinese: "廴", mean: "bước dài, dẫn đi", pronunciation: "dỉn", pinyin: "yǐn", sino_vietnamese: "dẫn" },
    { chinese: "弓", mean: "cây cung", pronunciation: "cung", pinyin: "gōng", sino_vietnamese: "cung" },
    { chinese: "彡", mean: "lông dài, tóc", pronunciation: "san", pinyin: "shān", sino_vietnamese: "sam" },
    { chinese: "戈", mean: "cây giáo, cây thương", pronunciation: "cưa", pinyin: "gē", sino_vietnamese: "qua" },
    { chinese: "月", mean: "mặt trăng", pronunciation: "duya", pinyin: "yuè", sino_vietnamese: "nguyệt" },
    { chinese: "示 (礻)", mean: "chỉ thị, thần linh (liên quan đến cúng bái, tôn giáo)", pronunciation: "sì", pinyin: "shì", sino_vietnamese: "thị" },
];