/*******************************
 * 1) DỮ LIỆU TỪ VỰNG (ví dụ)
 * Thay/ví dụ bằng 1000 từ của bạn.
 *******************************/
const sentence = [
    //    { index: "", english: "", mean: "", pronunciation: "" },
    { index: "1", english: "How are you ?", mean: "Bạn khỏe không ?" },
    { index: "2", english: "I'm fine, thank you.", mean: "Tôi khỏe, cảm ơn bạn." },
    { index: "3", english: "What your name?", mean: "Bạn tên gì?" },
    { index: "4", english: "My name is Thinh.", mean: "Tôi tên là Thịnh." },
    { index: "5", english: "How old are you?", mean: "Bạn bao nhiêu tuổi?" },
    { index: "6", english: "I am 25 years old.", mean: "Tôi năm nay 25 tuổi." },
    { index: "7", english: "This is my teacher, Ms Brown.", mean: "Đây là giáo viên của tôi, cô Brown." },
    { index: "8", english: "Is that your friend?", mean: "Đó có phải là bạn của bạn không?" },
    { index: "9", english: "No, it isn't.", mean: "Không, không phải." },
    { index: "10", english: "What colour is your pen?", mean: "Cây bút của bạn màu gì?" },
    { index: "11", english: "It's brown.", mean: "Nó màu nâu." },
    { index: "12", english: "It's nice!", mean: "Nó đẹp!" },
    { index: "13", english: "Touch your ear!", mean: "Chạm vào tai của bạn!" },
    { index: "14", english: "Open your eyes.", mean: "Mở mắt ra." },
    { index: "15", english: "Let's play a game.", mean: "Chúng ta cùng chơi một trò chơi nhé." },
    { index: "16", english: "What's your hobby?", mean: "Sở thích của bạn là gì?" },
    { index: "17", english: "I like walking.", mean: "Tôi thích đi bộ." },
    { index: "18", english: "Let's go to the classroom.", mean: "Chúng ta hãy đi đến lớp học." },
    { index: "19", english: "Is this our library?", mean: "Đây có phải là thư viện của chúng ta không?" },
    { index: "20", english: "We love our friend.", mean: "Chúng tôi yêu quý người bạn của mình." },
    { index: "21", english: "Close your book, please.", mean: "Vui lòng đóng sách của bạn lại." },
    { index: "22", english: "May I close my book?", mean: "Tôi có thể đóng sách của mình lại được không?" },
    { index: "23", english: "Sit down, please.", mean: "Vui lòng ngồi xuống." },
    { index: "24", english: "Stand up, please.", mean: "Vui lòng đứng lên." },
    { index: "25", english: "Let's come in the room.", mean: "Chúng ta hãy vào phòng." },
    { index: "26", english: "May I speak Vietnamese, please?", mean: "Tôi có thể nói tiếng Việt được không?" },
    { index: "27", english: "Do you like reading books?", mean: "Bạn có thích đọc sách không?" },
    { index: "28", english: "Do you have a ruler?", mean: "Bạn có thước kẻ không?" },
    { index: "29", english: "Yes, I do.", mean: "Có, tôi có." },
    { index: "30", english: "What colour is the eraser?", mean: "Cục tẩy màu gì?" },
    { index: "31", english: "I have a pencil case.", mean: "Tôi có một hộp bút." },
    { index: "32", english: "I play badminton at break time.", mean: "Tôi chơi cầu lông vào giờ ra chơi." },
    { index: "33", english: "I do word puzzles.", mean: "Tôi chơi trò giải ô chữ." },
    { index: "34", english: "Is your mother a worker?", mean: "Mẹ của bạn có phải là công nhân không?" },
    { index: "35", english: "What about your family?", mean: "Còn gia đình của bạn thì sao?" },
    { index: "36", english: "The bedroom is here.", mean: "Phòng ngủ ở đây." },
    { index: "37", english: "The lamps are on the table.", mean: "Những chiếc đèn ở trên bàn." },
    { index: "38", english: "Where is the living room?", mean: "Phòng khách ở đâu?" },
    { index: "39", english: "Look at the table and two chairs in my bedroom.", mean: "Hãy nhìn vào cái bàn và hai chiếc ghế trong phòng ngủ của tôi." },
    { index: "40", english: "There are two chairs.", mean: "Có hai cái ghế." },
    { index: "41", english: "What would you like to drink?", mean: "Bạn muốn uống gì?" },
    { index: "42", english: "Would you like some water?", mean: "Bạn có muốn uống một ít nước không?" },
    { index: "43", english: "There are a lot of food and drinks on the table.", mean: "Có rất nhiều đồ ăn và thức uống trên bàn." },
    { index: "44", english: "I would like some milk, please.", mean: "Tôi muốn một ít sữa." },
    { index: "45", english: "I have three rabbits.", mean: "Tôi có ba con thỏ." },
    { index: "46", english: "Do you have any parrots?", mean: "Bạn có con vẹt nào không?" },
    { index: "47", english: "How many birds do you have?", mean: "Bạn có bao nhiêu con chim?" },
    { index: "48", english: "Today I'm in the park with my friends.", mean: "Hôm nay tôi ở công viên với những người bạn của tôi." },
    { index: "49", english: "We have a lot of fun in the park.", mean: "Chúng tôi có rất nhiều niềm vui ở công viên." },
    { index: "50", english: "She is from America.", mean: "Cô ấy đến từ Mỹ." },
    { index: "51", english: "Where is he from?", mean: "Anh ấy đến từ đâu?" },
    { index: "52", english: "I go to bed at nine o'clock.", mean: "Tôi đi ngủ lúc chín giờ." },
    { index: "53", english: "I get up at six thirty.", mean: "Tôi thức dậy lúc sáu giờ ba mươi." },
    { index: "54", english: "What time do you have dinner?", mean: "Bạn ăn tối lúc mấy giờ?" },
    { index: "55", english: "I do housework on Sundays.", mean: "Tôi làm việc nhà vào Chủ nhật." },
    { index: "56", english: "What do you do on Mondays?", mean: "Bạn làm gì vào thứ Hai?" },
    { index: "57", english: "What day is it today?", mean: "Hôm nay là thứ mấy?" },
    { index: "58", english: "When is your birthday?", mean: "Sinh nhật của bạn là khi nào?" },
    { index: "59", english: "My little sister cannot ride a bike.", mean: "Em gái nhỏ của tôi không thể đi xe đạp." },
    { index: "60", english: "He can roller skate very well.", mean: "Cậu ấy có thể trượt patin rất giỏi." },


    
];