/*******************************
 * 1) DỮ LIỆU TỪ VỰNG (ví dụ)
 * Thay/ví dụ bằng 1000 từ của bạn.
 *******************************/
const sentence = [
    //    { index: "", english: "", mean: "", pronunciation: "" },
    { index: "1", english: "How are you ?", mean: "Bạn khỏe không ?" },
    { index: "2", english: "I'm fine, thank you.", mean: "Tôi khỏe, cảm ơn bạn." },
    { index: "3", english: "What your name?", mean: "Bạn tên gì?" },
    { index: "4", english: "My name is Thinh.", mean: "Tôi tên là Thịnh." },
    { index: "5", english: "How old are you?", mean: "Bạn bao nhiêu tuổi?" },
    { index: "6", english: "I am 25 years old.", mean: "Tôi năm nay 25 tuổi." },
    { index: "7", english: "This is my teacher, Ms Brown.", mean: "Đây là giáo viên của tôi, cô Brown." },
    { index: "8", english: "Is that your friend?", mean: "Đó có phải là bạn của bạn không?" },
    { index: "9", english: "No, it isn't.", mean: "Không, không phải." },
    { index: "10", english: "What colour is your pen?", mean: "Cây bút của bạn màu gì?" },
    { index: "11", english: "It's brown.", mean: "Nó màu nâu." },
    { index: "12", english: "It's nice!", mean: "Nó đẹp!" },
    { index: "13", english: "Touch your ear!", mean: "Chạm vào tai của bạn!" },
    { index: "14", english: "Open your eyes.", mean: "Mở mắt ra." },
    { index: "15", english: "Let's play a game.", mean: "Chúng ta cùng chơi một trò chơi nhé." },
    { index: "16", english: "What's your hobby?", mean: "Sở thích của bạn là gì?" },
    { index: "17", english: "I like walking.", mean: "Tôi thích đi bộ." },
    { index: "18", english: "Let's go to the classroom.", mean: "Chúng ta hãy đi đến lớp học." },
    { index: "19", english: "Is this our library?", mean: "Đây có phải là thư viện của chúng ta không?" },
    { index: "20", english: "We love our friend.", mean: "Chúng tôi yêu quý người bạn của mình." },
    { index: "21", english: "Close your book, please.", mean: "Vui lòng đóng sách của bạn lại." },
    { index: "22", english: "May I close my book?", mean: "Tôi có thể đóng sách của mình lại được không?" },
    { index: "23", english: "Sit down, please.", mean: "Vui lòng ngồi xuống." },
    { index: "24", english: "Stand up, please.", mean: "Vui lòng đứng lên." },
    { index: "25", english: "Let's come in the room.", mean: "Chúng ta hãy vào phòng." },
    { index: "26", english: "May I speak Vietnamese, please?", mean: "Tôi có thể nói tiếng Việt được không?" },
    { index: "27", english: "Do you like reading books?", mean: "Bạn có thích đọc sách không?" },
    { index: "28", english: "Do you have a ruler?", mean: "Bạn có thước kẻ không?" },
    { index: "29", english: "Yes, I do.", mean: "Có, tôi có." },
    { index: "30", english: "What colour is the eraser?", mean: "Cục tẩy màu gì?" },
    { index: "31", english: "I have a pencil case.", mean: "Tôi có một hộp bút." },
];