/*******************************
 * 1) DỮ LIỆU TỪ VỰNG (ví dụ)
 * Thay/ví dụ bằng 1000 từ của bạn.
 *******************************/
// noun
// pronoun
// verb
// adjective
// adverb
// preposition
// conjunction
// interjection
const vocabularyList = [
    //    // { index: "", english: "", mean: "", pronunciation: "", partOfSpeech: "" },
    // Class 1
    { index: "1", english: "tea", mean: "trà", pronunciation: "UK: /tiː/ | US: /tiː/", partOfSpeech: "noun" },
    { index: "2", english: "coffee", mean: "cà phê", pronunciation: "UK: /ˈkɒfi/ | US: /ˈkɔːfi/", partOfSpeech: "noun" },
    { index: "3", english: "welcome", mean: "chào mừng", pronunciation: "UK: /ˈwelkəm/ | US: /ˈwelkəm/", partOfSpeech: "verb, adjective, interjection" },
    { index: "4", english: "please", mean: "vui lòng, làm ơn", pronunciation: "UK: /pliːz/ | US: /pliːz/", partOfSpeech: "interjection, verb" },
    { index: "5", english: "or", mean: "hoặc", pronunciation: "UK: /ɔː/ | US: /ɔːr/", partOfSpeech: "conjunction" },
    { index: "6", english: "sugar", mean: "đường", pronunciation: "UK: /ˈʃʊɡə/ | US: /ˈʃʊɡər/", partOfSpeech: "noun" },
    { index: "7", english: "milk", mean: "sữa", pronunciation: "UK: /mɪlk/ | US: /mɪlk/", partOfSpeech: "noun" },
    { index: "8", english: "with", mean: "với", pronunciation: "UK: /wɪð/ | US: /wɪð/", partOfSpeech: "preposition" },
    { index: "9", english: "water", mean: "nước", pronunciation: "UK: /ˈwɔːtə/ | US: /ˈwɔːtər/", partOfSpeech: "noun" },
    { index: "10", english: "goodbye", mean: "tạm biệt", pronunciation: "UK: /ˌɡʊdˈbaɪ/ | US: /ˌɡʊdˈbaɪ/", partOfSpeech: "interjection, noun" },
    { index: "11", english: "and", mean: "và", pronunciation: "UK: /ænd/ | US: /ænd/", partOfSpeech: "conjunction" },
    { index: "12", english: "thank you", mean: "cảm ơn", pronunciation: "UK: /ˈθæŋk juː/ | US: /ˈθæŋk juː/", partOfSpeech: "interjection" },
    { index: "13", english: "Ball", mean: "Quả bóng", pronunciation: "/bɔːl/", partOfSpeech: "Noun" },
    { index: "14", english: "Bike", mean: "Xe đạp", pronunciation: "/baɪk/", partOfSpeech: "Noun" },
    { index: "15", english: "Book", mean: "Sách", pronunciation: "/bʊk/", partOfSpeech: "Noun" },
    { index: "16", english: "School", mean: "Trường học", pronunciation: "/skuːl/", partOfSpeech: "Noun" },
    { index: "17", english: "Play", mean: "Chơi", pronunciation: "/pleɪ/", partOfSpeech: "Verb" },
    { index: "18", english: "Ground", mean: "Mặt đất", pronunciation: "/ɡraʊnd/", partOfSpeech: "Noun" },
    { index: "19", english: "Playground", mean: "Sân chơi", pronunciation: "/ˈpleɪɡraʊnd/", partOfSpeech: "Noun" },
    { index: "20", english: "Listen", mean: "Lắng nghe", pronunciation: "/ˈlɪsən/", partOfSpeech: "Verb" },
    { index: "21", english: "Repeat", mean: "Lặp lại", pronunciation: "/rɪˈpiːt/", partOfSpeech: "Verb" },
    { index: "22", english: "In", mean: "Trong", pronunciation: "/ɪn/", partOfSpeech: "Preposition" },
    { index: "23", english: "Point", mean: "Điểm; chỉ vào", pronunciation: "/pɔɪnt/", partOfSpeech: "Noun / Verb" },
    { index: "24", english: "Say", mean: "Nói", pronunciation: "/seɪ/", partOfSpeech: "Verb" },
    { index: "25", english: "Lesson", mean: "Bài học", pronunciation: "/ˈlesən/", partOfSpeech: "Noun" },
    { index: "26", english: "Unit", mean: "Đơn vị; bài học", pronunciation: "/ˈjuːnɪt/", partOfSpeech: "Noun" },
    { index: "27", english: "Let", mean: "Cho phép; để", pronunciation: "/let/", partOfSpeech: "Verb" },
    { index: "28", english: "Talk", mean: "Nói chuyện", pronunciation: "/tɔːk/", partOfSpeech: "Verb" },
    { index: "29", english: "Sing", mean: "Hát", pronunciation: "/sɪŋ/", partOfSpeech: "Verb" },
    { index: "30", english: "Chant", mean: "Hô; hát theo nhịp, tụng kinh", pronunciation: "/tʃɑːnt/", partOfSpeech: "Verb / Noun" },
    { index: "31", english: "Tick", mean: "Đánh dấu ✓; tích", pronunciation: "/tɪk/", partOfSpeech: "Verb / Noun" },
    { index: "32", english: "Look", mean: "Nhìn", pronunciation: "/lʊk/", partOfSpeech: "Verb" },
    { index: "33", english: "Trace", mean: "Đồ theo; lần theo dấu vết, theo dõi", pronunciation: "/treɪs/", partOfSpeech: "Verb / Noun" },
    { index: "34", english: "Room", mean: "Phòng; không gian", pronunciation: "/ruːm/", partOfSpeech: "Noun" },
    { index: "35", english: "Dining", mean: "Ăn uống; dùng bữa", pronunciation: "/ˈdaɪnɪŋ/", partOfSpeech: "Noun / Adjective" },
    { index: "36", english: "Dining room", mean: "Phòng ăn", pronunciation: "/ˈdaɪnɪŋ ruːm/", partOfSpeech: "Noun" },
    { index: "37", english: "Extra", mean: "Thêm; bổ sung; dư", pronunciation: "/ˈekstrə/", partOfSpeech: "Adjective / Noun" },
    { index: "38", english: "Resource", mean: "Tài nguyên; nguồn lực", pronunciation: "/rɪˈsɔːrs/", partOfSpeech: "Noun" },
    { index: "39", english: "Glossary", mean: "Bảng chú giải; danh mục từ, bảng thuật ngữ", pronunciation: "/ˈɡlɒsəri/", partOfSpeech: "Noun" },
    { index: "40", english: "Cup", mean: "Cốc; tách", pronunciation: "/kʌp/", partOfSpeech: "Noun" },
    { index: "41", english: "Car", mean: "Xe hơi; ô tô", pronunciation: "/kɑːr/", partOfSpeech: "Noun" },
    { index: "42", english: "Cat", mean: "Con mèo", pronunciation: "/kæt/", partOfSpeech: "Noun" },
    { index: "43", english: "Cake", mean: "Bánh ngọt; bánh", pronunciation: "/keɪk/", partOfSpeech: "Noun" },
    { index: "44", english: "Load", mean: "Tải; chất hàng", pronunciation: "/ləʊd/", partOfSpeech: "Verb / Noun" },
    { index: "45", english: "Loading", mean: "Đang tải", pronunciation: "/ˈləʊdɪŋ/", partOfSpeech: "Noun / Adjective" },
    { index: "46", english: "Fun", mean: "Vui vẻ; niềm vui", pronunciation: "/fʌn/", partOfSpeech: "Noun / Adjective" },
    { index: "47", english: "Time", mean: "Thời gian; lần", pronunciation: "/taɪm/", partOfSpeech: "Noun" },
    { index: "48", english: "Find", mean: "Tìm; tìm thấy", pronunciation: "/faɪnd/", partOfSpeech: "Verb" },
    { index: "49", english: "Circle", mean: "Khoanh tròn; hình tròn", pronunciation: "/ˈsɜːrkəl/", partOfSpeech: "Verb / Noun" },
    { index: "50", english: "Then", mean: "Sau đó; rồi", pronunciation: "/ðen/", partOfSpeech: "Adverb" },
    { index: "51", english: "Color", mean: "Màu sắc; tô màu", pronunciation: "/ˈkʌlər/", partOfSpeech: "Noun / Verb" },
    { index: "52", english: "Colour", mean: "Màu sắc; tô màu", pronunciation: "/ˈkʌlər/", partOfSpeech: "Noun / Verb" },
    { index: "53", english: "Activity", mean: "Hoạt động", pronunciation: "/ækˈtɪvəti/", partOfSpeech: "Noun" },
    { index: "54", english: "Level", mean: "Cấp độ; mức độ; tầng", pronunciation: "/ˈlevəl/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "55", english: "Little", mean: "Nhỏ; ít", pronunciation: "/ˈlɪtəl/", partOfSpeech: "Adjective / Adverb / Determiner" },
    { index: "56", english: "Big", mean: "To; lớn", pronunciation: "/bɪɡ/", partOfSpeech: "Adjective" },
    { index: "57", english: "Show", mean: "Cho xem; trình diễn", pronunciation: "/ʃəʊ/", partOfSpeech: "Verb / Noun" },
    { index: "58", english: "Happy", mean: "Vui vẻ; hạnh phúc", pronunciation: "/ˈhæpi/", partOfSpeech: "Adjective" },
    { index: "59", english: "Street", mean: "Đường phố", pronunciation: "/striːt/", partOfSpeech: "Noun" },
    { index: "60", english: "Market", mean: "Chợ; thị trường", pronunciation: "/ˈmɑːrkɪt/", partOfSpeech: "Noun" },
    { index: "61", english: "Global", mean: "Toàn cầu", pronunciation: "/ˈɡləʊbəl/", partOfSpeech: "Adjective" },
    { index: "62", english: "Success", mean: "Thành công", pronunciation: "/səkˈses/", partOfSpeech: "Noun" },
    { index: "63", english: "Hat", mean: "Mũ; nón", pronunciation: "/hæt/", partOfSpeech: "Noun" },
    { index: "64", english: "Apple", mean: "Quả táo", pronunciation: "/ˈæpəl/", partOfSpeech: "Noun" },
    { index: "65", english: "Can", mean: "Có thể; có khả năng; được phép; lon; hộp; đóng hộp", pronunciation: "/kæn/", partOfSpeech: "Modal Verb / Noun / Verb" },
    { index: "66", english: "Bag", mean: "Túi; cặp", pronunciation: "/bæɡ/", partOfSpeech: "Noun" },
    { index: "67", english: "On", mean: "Trên; ở trên", pronunciation: "/ɒn/", partOfSpeech: "Preposition / Adverb" },
    { index: "68", english: "There", mean: "Ở đó; kia", pronunciation: "/ðer/", partOfSpeech: "Adverb" },
    { index: "69", english: "This", mean: "Này; cái này", pronunciation: "/ðɪs/", partOfSpeech: "Determiner / Pronoun" },
    { index: "70", english: "Those", mean: "Những cái đó; những người đó", pronunciation: "/ðəʊz/", partOfSpeech: "Determiner / Pronoun" },
    { index: "71", english: "Orange", mean: "Quả cam; màu cam", pronunciation: "/ˈɒrɪndʒ/", partOfSpeech: "Noun / Adjective" },
    { index: "72", english: "Bed", mean: "Giường; luống (cây); đáy (sông, biển); lớp, tầng", pronunciation: "/bed/", partOfSpeech: "Noun / Verb" },
    { index: "73", english: "Bedroom", mean: "Phòng ngủ", pronunciation: "/ˈbedruːm/", partOfSpeech: "Noun" },
    { index: "74", english: "Door", mean: "Cửa; lối vào; cánh cửa", pronunciation: "/dɔːr/", partOfSpeech: "Noun" },
    { index: "75", english: "Duck", mean: "Con vịt; cúi xuống, né; tránh", pronunciation: "/dʌk/", partOfSpeech: "Noun / Verb" },
    { index: "76", english: "Desk", mean: "Bàn làm việc; bàn học", pronunciation: "/desk/", partOfSpeech: "Noun" },
    { index: "77", english: "Dog", mean: "Con chó; theo dõi, bám theo; đối xử tệ", pronunciation: "/dɔːɡ/", partOfSpeech: "Noun / Verb" },
    { index: "78", english: "Very", mean: "Rất; chính là; đúng là", pronunciation: "/ˈveri/", partOfSpeech: "Adverb / Adjective" },
    { index: "79", english: "Easy", mean: "Dễ; dễ dàng; thoải mái; thư giãn; bình tĩnh", pronunciation: "/ˈiːzi/", partOfSpeech: "Adjective / Adverb" },
    { index: "80", english: "Near", mean: "Gần; gần như; đến gần; gần đây", pronunciation: "/nɪər/", partOfSpeech: "Preposition / Adjective / Adverb / Verb" },
    { index: "81", english: "Window", mean: "Cửa sổ; khoảng thời gian; cửa sổ trên màn hình", pronunciation: "/ˈwɪndəʊ/", partOfSpeech: "Noun" },
    { index: "82", english: "Self", mean: "Bản thân; chính mình; cái tôi", pronunciation: "/self/", partOfSpeech: "Noun" },
    { index: "83", english: "Check", mean: "Kiểm tra; kiểm soát; đánh dấu ✓; hóa đơn; séc; kiểm tra lại", pronunciation: "/tʃek/", partOfSpeech: "Verb / Noun" },
    { index: "84", english: "Cross", mean: "Băng qua; đi ngang qua; vượt qua; bắt chéo; dấu thập; chữ thập; khó chịu; lai", pronunciation: "/krɒs/", partOfSpeech: "Verb / Noun / Adjective" },
    { index: "85", english: "Super", mean: "Siêu; tuyệt vời; rất tốt; người giám sát; siêu thị (viết tắt)", pronunciation: "/ˈsuːpər/", partOfSpeech: "Adjective / Adverb / Noun" },
    { index: "86", english: "At", mean: "Ở; tại; vào (thời điểm); với; trong (một hoạt động/trạng thái)", pronunciation: "/æt/", partOfSpeech: "Preposition" },
    { index: "87", english: "Fish", mean: "Cá; con cá; câu cá", pronunciation: "/fɪʃ/", partOfSpeech: "Noun / Verb" },
    { index: "88", english: "Chips", mean: "Khoai tây chiên; khoai lát chiên; vi mạch, chip điện tử", pronunciation: "/tʃɪps/", partOfSpeech: "Noun" },
    { index: "89", english: "Shop", mean: "Cửa hàng; cửa hiệu; mua sắm; mua", pronunciation: "/ʃɒp/", partOfSpeech: "Noun / Verb" },
    { index: "90", english: "Chicken", mean: "Con gà; thịt gà; người nhát gan", pronunciation: "/ˈtʃɪkɪn/", partOfSpeech: "Noun / Adjective" },
    { index: "91", english: "Milk", mean: "Sữa; vắt sữa; khai thác, tận dụng", pronunciation: "/mɪlk/", partOfSpeech: "Noun / Verb" },
    { index: "92", english: "Like", mean: "Thích; giống như; như là; ví dụ như; kiểu, dạng; sự thích thú", pronunciation: "/laɪk/", partOfSpeech: "Verb / Preposition / Adjective / Noun / Conjunction" },
    { index: "93", english: "Class", mean: "Lớp học; lớp; tiết học; tầng lớp; loại, hạng; đẳng cấp; phân loại", pronunciation: "/klɑːs/", partOfSpeech: "Noun / Verb" },
    { index: "94", english: "Classroom", mean: "Phòng học; lớp học", pronunciation: "/ˈklɑːsruːm/", partOfSpeech: "Noun" },
    { index: "95", english: "Red", mean: "Màu đỏ; đỏ; tức giận; màu đỏ (trong chính trị/chủ nghĩa cộng sản)", pronunciation: "/red/", partOfSpeech: "Noun / Adjective" },
    { index: "96", english: "Pen", mean: "Bút; chuồng, khu quây nhốt động vật; viết bằng bút", pronunciation: "/pen/", partOfSpeech: "Noun / Verb" },
    { index: "97", english: "Pencil", mean: "Bút chì; viết bằng bút chì", pronunciation: "/ˈpensəl/", partOfSpeech: "Noun / Verb" },
    { index: "98", english: "Bell", mean: "Chuông; tiếng chuông; chuông điện thoại; rung chuông", pronunciation: "/bel/", partOfSpeech: "Noun / Verb" },
    { index: "99", english: "How", mean: "Như thế nào; bằng cách nào; bao nhiêu; đến mức nào; thế nào mà; rất, biết bao", pronunciation: "/haʊ/", partOfSpeech: "Adverb / Conjunction" },
    { index: "100", english: "Many", mean: "Nhiều; nhiều người/nhiều thứ", pronunciation: "/ˈmeni/", partOfSpeech: "Determiner / Pronoun / Adjective" },
    { index: "101", english: "People", mean: "Mọi người; người dân; người; dân tộc, cộng đồng", pronunciation: "/ˈpiːpəl/", partOfSpeech: "Noun" },
    { index: "102", english: "He", mean: "Anh ấy; ông ấy; cậu ấy", pronunciation: "/hiː/", partOfSpeech: "Pronoun" },
    { index: "103", english: "She", mean: "Cô ấy; bà ấy; chị ấy", pronunciation: "/ʃiː/", partOfSpeech: "Pronoun" },
    { index: "104", english: "Her", mean: "Cô ấy; bà ấy; chị ấy; của cô ấy, của bà ấy, của chị ấy", pronunciation: "/hɜːr/", partOfSpeech: "Pronoun / Determiner" },
    { index: "105", english: "Him", mean: "Anh ấy; ông ấy; cậu ấy (tân ngữ)", pronunciation: "/hɪm/", partOfSpeech: "Pronoun" },
    { index: "106", english: "It", mean: "Nó; điều đó; việc đó; con vật/đồ vật đó", pronunciation: "/ɪt/", partOfSpeech: "Pronoun" },
    { index: "107", english: "Have", mean: "Có; sở hữu; ăn/uống; trải qua; mắc (bệnh); tổ chức; nhận; phải, cần; khiến/nhờ ai làm gì", pronunciation: "/hæv/", partOfSpeech: "Verb" },
    { index: "108", english: "Match", mean: "Ghép, nối; phù hợp; trận đấu; que diêm; sự tương xứng", pronunciation: "/mætʃ/", partOfSpeech: "Verb / Noun" },
    { index: "109", english: "Write", mean: "Viết; ghi; viết thư; sáng tác; viết ra, ghi lại", pronunciation: "/raɪt/", partOfSpeech: "Verb" },
    { index: "110", english: "Air", mean: "Không khí; bầu không khí; vẻ ngoài, phong thái; phát sóng; thông gió", pronunciation: "/eər/", partOfSpeech: "Noun / Verb" },
    { index: "111", english: "Draw", mean: "Vẽ; kéo; lôi; rút; lấy; thu hút; hòa (trận đấu); rút ra, suy ra", pronunciation: "/drɔː/", partOfSpeech: "Verb / Noun" },
    { index: "112", english: "Idea", mean: "Ý tưởng; ý kiến; quan niệm; ý niệm; suy nghĩ", pronunciation: "/aɪˈdɪə/", partOfSpeech: "Noun" },
    { index: "113", english: "Team", mean: "Đội; nhóm; đội ngũ; hợp tác, phối hợp", pronunciation: "/tiːm/", partOfSpeech: "Noun / Verb" },
    { index: "114", english: "Make", mean: "Làm; tạo ra; chế tạo; khiến; làm cho; kiếm (tiền); chuẩn bị; quyết định; đạt được; trở thành; hiểu, nhận ra", pronunciation: "/meɪk/", partOfSpeech: "Verb / Noun" },
    { index: "115", english: "Sentence", mean: "Câu; câu văn; bản án; tuyên án", pronunciation: "/ˈsentəns/", partOfSpeech: "Noun / Verb" },
    { index: "116", english: "Slap", mean: "Tát; vỗ; đánh nhẹ; cái tát; tiếng bốp; đặt mạnh, đặt phịch", pronunciation: "/slæp/", partOfSpeech: "Verb / Noun / Adverb" },
    { index: "117", english: "Board", mean: "Bảng; tấm ván; hội đồng quản trị; lên (tàu, máy bay); ăn ở, trọ; lên máy bay/tàu", pronunciation: "/bɔːrd/", partOfSpeech: "Noun / Verb" },
    { index: "118", english: "Garden", mean: "Khu vườn; làm vườn; trồng cây", pronunciation: "/ˈɡɑːrdən/", partOfSpeech: "Noun / Verb" },
    { index: "119", english: "Boy", mean: "Cậu bé; con trai; chàng trai", pronunciation: "/bɔɪ/", partOfSpeech: "Noun" },
    { index: "120", english: "Girl", mean: "Cô bé; con gái; cô gái", pronunciation: "/ɡɜːrl/", partOfSpeech: "Noun" },
    { index: "121", english: "Goat", mean: "Con dê; người ngốc, người bị đem ra làm trò cười", pronunciation: "/ɡəʊt/", partOfSpeech: "Noun" },
    { index: "122", english: "Gate", mean: "Cổng; cửa; lối vào; kiểm soát/cấm vào", pronunciation: "/ɡeɪt/", partOfSpeech: "Noun / Verb" },
    { index: "123", english: "Park", mean: "Công viên; bãi đỗ xe; đỗ xe; đặt, để", pronunciation: "/pɑːrk/", partOfSpeech: "Noun / Verb" },
    { index: "124", english: "Head", mean: "Đầu; người đứng đầu; thủ lĩnh; phần đầu; đầu mối; đầu trang; đi về phía; dẫn đầu; chỉ huy", pronunciation: "/hed/", partOfSpeech: "Noun / Verb / Adjective" },
    { index: "125", english: "Hand", mean: "Bàn tay; tay; người giúp việc; kim đồng hồ; người lao động; trao, đưa; giúp đỡ; giao, chuyển", pronunciation: "/hænd/", partOfSpeech: "Noun / Verb" },
    { index: "126", english: "Hair", mean: "Tóc; sợi lông; lông trên cơ thể", pronunciation: "/her/", partOfSpeech: "Noun" },
    { index: "127", english: "Horse", mean: "Con ngựa; cưỡi ngựa; chơi ngựa", pronunciation: "/hɔːrs/", partOfSpeech: "Noun / Verb" },
    { index: "128", english: "Touch", mean: "Chạm; sờ; đụng; cảm ứng; liên lạc; ảnh hưởng; cảm động; cái chạm; sự tiếp xúc; nét, dấu vết", pronunciation: "/tʌtʃ/", partOfSpeech: "Verb / Noun" },
    { index: "129", english: "Your", mean: "Của bạn; của các bạn; của anh/chị; của ông/bà", pronunciation: "/jʊər/", partOfSpeech: "Determiner" },
    { index: "130", english: "Out", mean: "Ra ngoài; ở ngoài; hết; không còn; tắt; công khai; không đúng; bị loại; xuất hiện", pronunciation: "/aʊt/", partOfSpeech: "Adverb / Preposition / Adjective" },
    { index: "131", english: "Look out", mean: "Coi chừng; cẩn thận; đề phòng", pronunciation: "/lʊk aʊt/", partOfSpeech: "Phrasal Verb" },
    { index: "132", english: "Lock", mean: "Khóa; ổ khóa; khóa lại; chải, cuộn (tóc); một mớ, cụm", pronunciation: "/lɒk/", partOfSpeech: "Noun / Verb" },
    { index: "133", english: "Clock", mean: "Đồng hồ; bấm giờ; đo thời gian", pronunciation: "/klɒk/", partOfSpeech: "Noun / Verb" },
    { index: "134", english: "Mop", mean: "Cây lau nhà; lau nhà; lau sạch", pronunciation: "/mɒp/", partOfSpeech: "Noun / Verb" },
    { index: "135", english: "Map", mean: "Bản đồ; lập bản đồ; vẽ bản đồ; biểu thị, mô tả", pronunciation: "/mæp/", partOfSpeech: "Noun / Verb" },
    { index: "136", english: "Pot", mean: "Nồi; chậu; bình; hũ; tiền thưởng; đặt vào nồi; trồng vào chậu", pronunciation: "/pɒt/", partOfSpeech: "Noun / Verb" },
    { index: "137", english: "Zoo", mean: "Sở thú; vườn thú; nơi hỗn loạn, lộn xộn", pronunciation: "/zuː/", partOfSpeech: "Noun" },
    { index: "138", english: "Mango", mean: "Quả xoài; cây xoài", pronunciation: "/ˈmæŋɡəʊ/", partOfSpeech: "Noun" },
    { index: "139", english: "Mouse", mean: "Con chuột; chuột máy tính; di chuyển bằng chuột máy tính", pronunciation: "/maʊs/", partOfSpeech: "Noun / Verb" },
    { index: "140", english: "Monkey", mean: "Con khỉ; bắt chước; trêu chọc, nghịch ngợm", pronunciation: "/ˈmʌŋki/", partOfSpeech: "Noun / Verb" },
    { index: "141", english: "Mother", mean: "Mẹ; mẹ đẻ; người mẹ; làm mẹ; sinh ra, nuôi dưỡng", pronunciation: "/ˈmʌðər/", partOfSpeech: "Noun / Verb" },
    { index: "142", english: "Father", mean: "Cha; bố; người sáng lập, người tạo ra; làm cha; tạo ra, sáng lập", pronunciation: "/ˈfɑːðər/", partOfSpeech: "Noun / Verb" },
    { index: "143", english: "For", mean: "Cho; dành cho; vì; bởi vì; để; trong khoảng (thời gian); đối với; thay cho", pronunciation: "/fɔːr/", partOfSpeech: "Preposition / Conjunction" },
    { index: "144", english: "That", mean: "Đó; kia; rằng; mà; cái đó; người đó; đến mức đó", pronunciation: "/ðæt/", partOfSpeech: "Determiner / Pronoun / Conjunction / Adverb" },
    { index: "145", english: "His", mean: "Của anh ấy; của ông ấy; của cậu ấy", pronunciation: "/hɪz/", partOfSpeech: "Determiner / Pronoun" },
    { index: "146", english: "My", mean: "Của tôi; của mình", pronunciation: "/maɪ/", partOfSpeech: "Determiner" },
    { index: "147", english: "Run", mean: "Chạy; điều hành; vận hành; diễn ra; kéo dài; chạy (máy); dòng chảy; chuỗi, đợt", pronunciation: "/rʌn/", partOfSpeech: "Verb / Noun" },
    { index: "148", english: "Jump", mean: "Nhảy; nhảy lên; nhảy qua; tăng vọt; cú nhảy; bước nhảy", pronunciation: "/dʒʌmp/", partOfSpeech: "Verb / Noun" },
    { index: "149", english: "Truck", mean: "Xe tải; xe chở hàng; vận chuyển bằng xe tải", pronunciation: "/trʌk/", partOfSpeech: "Noun / Verb" },
    { index: "150", english: "Sun", mean: "Mặt trời; ánh nắng; ánh sáng mặt trời", pronunciation: "/sʌn/", partOfSpeech: "Noun / Verb" },
    { index: "151", english: "Sunny", mean: "Có nắng; nhiều nắng; tươi sáng; vui vẻ, lạc quan", pronunciation: "/ˈsʌni/", partOfSpeech: "Adjective" },
    { index: "152", english: "Bus", mean: "Xe buýt; đưa đón bằng xe buýt; dọn bàn (nhà hàng)", pronunciation: "/bʌs/", partOfSpeech: "Noun / Verb" },
    { index: "153", english: "Stop", mean: "Dừng; ngừng; ngăn chặn; trạm, điểm dừng; sự dừng lại; dấu chấm", pronunciation: "/stɒp/", partOfSpeech: "Verb / Noun" },
    { index: "154", english: "Move", mean: "Di chuyển; chuyển chỗ; dọn đi; chuyển động; tiến triển; hành động; nước đi", pronunciation: "/muːv/", partOfSpeech: "Verb / Noun" },
    { index: "155", english: "To", mean: "Đến; tới; hướng tới; đối với; để; nhằm; cho đến", pronunciation: "/tuː/", partOfSpeech: "Preposition / Infinitive Marker" },
    { index: "156", english: "Today", mean: "Hôm nay; ngày hôm nay; thời nay; ngày nay", pronunciation: "/təˈdeɪ/", partOfSpeech: "Adverb / Noun" },
    { index: "157", english: "Lake", mean: "Hồ; mặt hồ", pronunciation: "/leɪk/", partOfSpeech: "Noun" },
    { index: "158", english: "Leaf", mean: "Lá cây; tờ, trang (sách); rời đi", pronunciation: "/liːf/", partOfSpeech: "Noun / Verb" },
    { index: "159", english: "Lemon", mean: "Quả chanh vàng; màu vàng chanh; thứ kém chất lượng", pronunciation: "/ˈlemən/", partOfSpeech: "Noun / Adjective" },
    { index: "160", english: "Round", mean: "Tròn; vòng; lượt; quanh; vòng quanh; đi vòng; làm tròn; hình tròn", pronunciation: "/raʊnd/", partOfSpeech: "Adjective / Noun / Preposition / Adverb / Verb" },
    { index: "161", english: "Fall", mean: "Rơi; ngã; rơi xuống; giảm; xảy ra; mùa thu; sự rơi/ngã; sự sụt giảm", pronunciation: "/fɔːl/", partOfSpeech: "Verb / Noun" },
    { index: "162", english: "Review", mean: "Xem lại; ôn tập; đánh giá; bài đánh giá; bài ôn tập; nhận xét", pronunciation: "/rɪˈvjuː/", partOfSpeech: "Verb / Noun" },
    { index: "163", english: "Word", mean: "Từ; lời nói; lời; tin tức; lời hứa; khẩu hiệu; thông tin", pronunciation: "/wɜːrd/", partOfSpeech: "Noun / Verb" },
    { index: "164", english: "Letter", mean: "Chữ cái; thư; bức thư; văn bản chính thức; ký hiệu; đạt thành tích thể thao", pronunciation: "/ˈletər/", partOfSpeech: "Noun / Verb" },
    { index: "165", english: "Canteen", mean: "Căng tin; nhà ăn; bình đựng nước", pronunciation: "/kænˈtiːn/", partOfSpeech: "Noun" },
    { index: "166", english: "Noodle", mean: "Mì; sợi mì; người ngốc nghếch (thân mật)", pronunciation: "/ˈnuːdəl/", partOfSpeech: "Noun / Verb" },
    { index: "167", english: "Nut", mean: "Hạt; quả hạch; đai ốc; người lập dị; người cuồng nhiệt", pronunciation: "/nʌt/", partOfSpeech: "Noun" },
    { index: "168", english: "Banana", mean: "Quả chuối; màu vàng nhạt; người ngớ ngẩn", pronunciation: "/bəˈnɑːnə/", partOfSpeech: "Noun" },
    { index: "169", english: "Toy", mean: "Đồ chơi; đồ vật dùng để giải trí; đồ chơi, vật không có giá trị thực tế", pronunciation: "/tɔɪ/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "170", english: "Store", mean: "Cửa hàng; kho; hàng tồn kho; lưu trữ; chứa", pronunciation: "/stɔːr/", partOfSpeech: "Noun / Verb" },
    { index: "171", english: "Top", mean: "Trên cùng; đỉnh; đầu; phần trên; hàng đầu; đứng đầu; vượt qua; phủ lên", pronunciation: "/tɒp/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "172", english: "Left", mean: "Bên trái; phía trái; đã rời đi; còn lại; để lại", pronunciation: "/left/", partOfSpeech: "Noun / Adjective / Adverb / Verb" },
    { index: "173", english: "Bottom", mean: "Đáy; dưới cùng; phần cuối; mông; thấp nhất; ở dưới cùng; chạm đáy", pronunciation: "/ˈbɒtəm/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "174", english: "Right", mean: "Bên phải; đúng; chính xác; quyền; bên phải; ngay lập tức; sửa chữa; đúng đắn", pronunciation: "/raɪt/", partOfSpeech: "Adjective / Adverb / Noun / Verb" },
    { index: "175", english: "Mid", mean: "Ở giữa; trung tâm; giữa", pronunciation: "/mɪd/", partOfSpeech: "Adjective / Noun / Preposition" },
    { index: "176", english: "Tiger", mean: "Con hổ; người mạnh mẽ, hung dữ", pronunciation: "/ˈtaɪɡər/", partOfSpeech: "Noun" },
    { index: "177", english: "Lion", mean: "Con sư tử; người nổi tiếng/quyền lực", pronunciation: "/ˈlaɪən/", partOfSpeech: "Noun" },
    { index: "178", english: "Teddy", mean: "Gấu bông; gấu Teddy", pronunciation: "/ˈtedi/", partOfSpeech: "Noun" },
    { index: "179", english: "Bear", mean: "Con gấu; chịu đựng; mang, vác; sinh ra; có, chứa; chịu trách nhiệm; tạo ra", pronunciation: "/ber/", partOfSpeech: "Noun / Verb" },
    { index: "180", english: "Turtle", mean: "Con rùa; làm việc chậm chạp", pronunciation: "/ˈtɜːrtəl/", partOfSpeech: "Noun / Verb" },
    { index: "181", english: "Hold", mean: "Cầm; giữ; nắm; tổ chức; chứa; chờ máy; giữ lại; quan điểm; khoang chứa; sự nắm giữ", pronunciation: "/həʊld/", partOfSpeech: "Verb / Noun" },
    { index: "182", english: "Shelf", mean: "Kệ; giá; ngăn kệ; thềm đá, gờ nhô ra", pronunciation: "/ʃelf/", partOfSpeech: "Noun" },
    { index: "183", english: "Foot", mean: "Bàn chân; chân; bàn chân (đơn vị đo); chân của đồ vật", pronunciation: "/fʊt/", partOfSpeech: "Noun / Verb" },
    { index: "184", english: "Football", mean: "Bóng đá; quả bóng đá", pronunciation: "/ˈfʊtbɔːl/", partOfSpeech: "Noun" },
    { index: "185", english: "Face", mean: "Khuôn mặt; mặt; bề mặt; đối mặt; hướng về; quay mặt về phía", pronunciation: "/feɪs/", partOfSpeech: "Noun / Verb" },
    { index: "186", english: "Love", mean: "Tình yêu; yêu; thích; người yêu; số 0 (trong quần vợt)", pronunciation: "/lʌv/", partOfSpeech: "Noun / Verb" },
    { index: "187", english: "Lovely", mean: "Đáng yêu; xinh đẹp; dễ chịu; tuyệt vời", pronunciation: "/ˈlʌvli/", partOfSpeech: "Adjective / Adverb" },
    { index: "188", english: "Watch", mean: "Xem; nhìn; theo dõi; canh chừng; đồng hồ đeo tay; sự theo dõi, canh gác", pronunciation: "/wɒtʃ/", partOfSpeech: "Verb / Noun" },
    { index: "189", english: "Home", mean: "Nhà; gia đình; quê nhà; nơi ở; về nhà; ở nhà; hướng về nhà; thuộc về nhà", pronunciation: "/həʊm/", partOfSpeech: "Noun / Adverb / Adjective / Verb" },
    { index: "190", english: "Wash", mean: "Rửa; giặt; tắm; rửa sạch; giặt giũ; nước rửa; sự giặt/rửa", pronunciation: "/wɒʃ/", partOfSpeech: "Verb / Noun" },
    { index: "191", english: "Feel", mean: "Cảm thấy; cảm nhận; sờ, chạm; có cảm giác; cảm giác; cảm nhận", pronunciation: "/fiːl/", partOfSpeech: "Verb / Noun" },
    { index: "192", english: "Fill", mean: "Lấp đầy; làm đầy; điền vào; đổ đầy; đảm nhiệm; lấp đầy chỗ trống; sự lấp đầy", pronunciation: "/fɪl/", partOfSpeech: "Verb / Noun" },
    { index: "193", english: "Blank", mean: "Trống; để trống; khoảng trống; chỗ trống; không nhớ được; vô cảm", pronunciation: "/blæŋk/", partOfSpeech: "Adjective / Noun / Verb" },
    { index: "194", english: "After", mean: "Sau; sau khi; phía sau; sau đó; theo sau; về sau", pronunciation: "/ˈɑːftər/", partOfSpeech: "Preposition / Conjunction / Adverb / Adjective" },
    { index: "195", english: "Correct", mean: "Đúng; chính xác; đúng đắn; sửa; chỉnh sửa; sửa cho đúng", pronunciation: "/kəˈrekt/", partOfSpeech: "Adjective / Verb" },
    { index: "196", english: "Question", mean: "Câu hỏi; vấn đề; câu hỏi nghi vấn; hỏi; chất vấn; nghi ngờ", pronunciation: "/ˈkwestʃən/", partOfSpeech: "Noun / Verb" },
    { index: "197", english: "Answer", mean: "Câu trả lời; đáp án; lời giải; trả lời; đáp lại; giải quyết", pronunciation: "/ˈɑːnsər/", partOfSpeech: "Noun / Verb" },
    { index: "198", english: "Revision", mean: "Sự ôn tập; sự xem xét lại; sự sửa đổi; bản chỉnh sửa", pronunciation: "/rɪˈvɪʒən/", partOfSpeech: "Noun" },
    { index: "199", english: "Term", mean: "Học kỳ; thuật ngữ; từ ngữ; thời hạn; nhiệm kỳ; điều khoản; gọi, đặt tên", pronunciation: "/tɜːrm/", partOfSpeech: "Noun / Verb" },
    { index: "200", english: "Put", mean: "Đặt; để; đặt vào; đưa; bỏ; diễn đạt; khiến; đặt cược; sự đặt cược", pronunciation: "/pʊt/", partOfSpeech: "Verb / Noun" },
    { index: "201", english: "Order", mean: "Thứ tự; trật tự; đơn hàng; mệnh lệnh; yêu cầu; gọi món; đặt hàng; ra lệnh; sắp xếp", pronunciation: "/ˈɔːrdər/", partOfSpeech: "Noun / Verb" },
    { index: "202", english: "Picture", mean: "Bức tranh; hình ảnh; ảnh; bức ảnh; hình dung; mô tả; tưởng tượng", pronunciation: "/ˈpɪktʃər/", partOfSpeech: "Noun / Verb" },
    // class 2
    { index: "203", english: "Birth", mean: "Sự sinh ra; sự ra đời; lúc sinh; nguồn gốc", pronunciation: "/bɜːrθ/", partOfSpeech: "Noun" },
    { index: "204", english: "Day", mean: "Ngày; ban ngày; thời gian; thời kỳ; ngày làm việc", pronunciation: "/deɪ/", partOfSpeech: "Noun" },
    { index: "205", english: "Birthday", mean: "Sinh nhật; ngày kỷ niệm ngày sinh", pronunciation: "/ˈbɜːrθdeɪ/", partOfSpeech: "Noun" },
    { index: "206", english: "Party", mean: "Bữa tiệc; buổi tiệc; đảng phái; nhóm, phe; tham gia tiệc; tổ chức tiệc", pronunciation: "/ˈpɑːrti/", partOfSpeech: "Noun / Verb" },
    { index: "207", english: "Popcorn", mean: "Bỏng ngô; bắp rang", pronunciation: "/ˈpɒpkɔːrn/", partOfSpeech: "Noun" },
    { index: "208", english: "Pasta", mean: "Mì Ý; các món làm từ bột mì ống", pronunciation: "/ˈpæstə/", partOfSpeech: "Noun" },
    { index: "209", english: "Yummy", mean: "Ngon; ngon miệng", pronunciation: "/ˈjʌmi/", partOfSpeech: "Adjective" },
    { index: "210", english: "Back", mean: "Lưng; phía sau; mặt sau; phía sau lưng; trở lại; quay lại; hỗ trợ; ủng hộ; lùi lại", pronunciation: "/bæk/", partOfSpeech: "Noun / Adjective / Adverb / Verb" },
    { index: "211", english: "Yard", mean: "Sân; khoảng sân; thước Anh; khu vực chứa/đỗ hàng hóa, phương tiện", pronunciation: "/jɑːrd/", partOfSpeech: "Noun" },
    { index: "212", english: "Backyard", mean: "Sân sau; khu vực phía sau nhà", pronunciation: "/ˌbækˈjɑːrd/", partOfSpeech: "Noun / Adjective" },
    { index: "213", english: "Kite", mean: "Con diều; thả diều; chim diều hâu", pronunciation: "/kaɪt/", partOfSpeech: "Noun / Verb" },
    { index: "214", english: "Kitten", mean: "Mèo con", pronunciation: "/ˈkɪtən/", partOfSpeech: "Noun" },
    { index: "215", english: "Fly", mean: "Bay; bay qua; lái máy bay; ruồi; chuyến bay; khóa kéo; bay nhanh; chạy trốn", pronunciation: "/flaɪ/", partOfSpeech: "Verb / Noun / Adjective" },
    { index: "216", english: "Ride", mean: "Cưỡi; đi (xe); chuyến đi; chuyến xe; cưỡi ngựa; trêu chọc, chế giễu", pronunciation: "/raɪd/", partOfSpeech: "Verb / Noun" },
    { index: "217", english: "Aloud", mean: "Thành tiếng; to, rõ ràng (khi nói/đọc)", pronunciation: "/əˈlaʊd/", partOfSpeech: "Adverb" },
    { index: "218", english: "Spell", mean: "Đánh vần; viết đúng chính tả; chính tả; khoảng thời gian; giai đoạn; thay phiên", pronunciation: "/spel/", partOfSpeech: "Verb / Noun" },
    { index: "219", english: "Chain", mean: "Dây chuyền; chuỗi; xích; một loạt; chuỗi cửa hàng; xích lại, buộc bằng xích", pronunciation: "/tʃeɪn/", partOfSpeech: "Noun / Verb" },
    { index: "220", english: "Sea", mean: "Biển; vùng biển; mặt biển; sóng biển", pronunciation: "/siː/", partOfSpeech: "Noun" },
    { index: "221", english: "Side", mean: "Bên; phía; mặt; cạnh; phe, bên; bên cạnh; đứng về phía; nghiêng về", pronunciation: "/saɪd/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "222", english: "Seaside", mean: "Bờ biển; vùng ven biển; thuộc về bờ biển", pronunciation: "/ˈsiːsaɪd/", partOfSpeech: "Noun / Adjective" },
    { index: "223", english: "Sail", mean: "Cánh buồm; chuyến đi bằng thuyền; đi thuyền; căng buồm; lướt đi", pronunciation: "/seɪl/", partOfSpeech: "Noun / Verb" },
    { index: "224", english: "Sand", mean: "Cát; bãi cát; rắc/phủ cát", pronunciation: "/sænd/", partOfSpeech: "Noun / Verb" },
    { index: "225", english: "Monday", mean: "Thứ Hai", pronunciation: "/ˈmʌndeɪ/", partOfSpeech: "Noun" },
    { index: "226", english: "Tuesday", mean: "Thứ Ba", pronunciation: "/ˈtjuːzdeɪ/", partOfSpeech: "Noun" },
    { index: "227", english: "Wednesday", mean: "Thứ Tư", pronunciation: "/ˈwenzdeɪ/", partOfSpeech: "Noun" },
    { index: "228", english: "Thursday", mean: "Thứ Năm", pronunciation: "/ˈθɜːrzdeɪ/", partOfSpeech: "Noun" },
    { index: "229", english: "Friday", mean: "Thứ Sáu", pronunciation: "/ˈfraɪdeɪ/", partOfSpeech: "Noun" },
    { index: "230", english: "Saturday", mean: "Thứ Bảy", pronunciation: "/ˈsætərdeɪ/", partOfSpeech: "Noun" },
    { index: "231", english: "Sunday", mean: "Chủ Nhật", pronunciation: "/ˈsʌndeɪ/", partOfSpeech: "Noun" },
    { index: "232", english: "Year", mean: "Năm; năm tuổi; niên đại; năm học", pronunciation: "/jɪər/", partOfSpeech: "Noun" },
    { index: "233", english: "Month", mean: "Tháng; khoảng một tháng", pronunciation: "/mʌnθ/", partOfSpeech: "Noun" },
    { index: "234", english: "Week", mean: "Tuần; tuần lễ; khoảng thời gian bảy ngày", pronunciation: "/wiːk/", partOfSpeech: "Noun" },
    { index: "235", english: "Weekend", mean: "Cuối tuần", pronunciation: "/ˌwiːkˈend/", partOfSpeech: "Noun" },
    { index: "236", english: "Country", mean: "Đất nước; quốc gia; vùng quê; nông thôn; vùng đất", pronunciation: "/ˈkʌntri/", partOfSpeech: "Noun" },
    { index: "237", english: "Countryside", mean: "Vùng nông thôn; miền quê; vùng quê", pronunciation: "/ˈkʌntrisaɪd/", partOfSpeech: "Noun" },
    { index: "238", english: "River", mean: "Sông; dòng sông", pronunciation: "/ˈrɪvər/", partOfSpeech: "Noun" },
    { index: "239", english: "Rain", mean: "Mưa; cơn mưa; mưa xuống; rơi như mưa; trút xuống", pronunciation: "/reɪn/", partOfSpeech: "Noun / Verb" },
    { index: "240", english: "Bow", mean: "Cúi chào; cúi người; cây cung; cái nơ; mũi tàu; cúi đầu; uốn cong", pronunciation: "/baʊ/; /boʊ/", partOfSpeech: "Noun / Verb" },
    { index: "241", english: "Rainbow", mean: "Cầu vồng; dải màu giống cầu vồng", pronunciation: "/ˈreɪnboʊ/", partOfSpeech: "Noun" },
    { index: "242", english: "Road", mean: "Con đường; đường đi; tuyến đường; cách thức, phương hướng", pronunciation: "/roʊd/", partOfSpeech: "Noun" },
    { index: "243", english: "Sky", mean: "Bầu trời; trời; bầu trời trong tranh/ảnh; đánh bóng lên cao", pronunciation: "/skaɪ/", partOfSpeech: "Noun / Verb" },
    { index: "244", english: "Cloud", mean: "Đám mây; mây; đám đông; khối lượng lớn; làm mờ; che phủ; khiến lo lắng/buồn phiền", pronunciation: "/klaʊd/", partOfSpeech: "Noun / Verb" },
    { index: "245", english: "Zero", mean: "Số không; không; điểm 0; mức bằng không", pronunciation: "/ˈzɪərəʊ/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "246", english: "One", mean: "Một; số một; một người/một vật; một cái; duy nhất; từng người/từng cái; một số người; đồng nhất", pronunciation: "/wʌn/", partOfSpeech: "Number / Pronoun / Determiner / Adjective" },
    { index: "247", english: "Two", mean: "Hai; số hai; hai người/hai vật; một đôi; hai điểm; số 2", pronunciation: "/tuː/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "248", english: "Three", mean: "Ba; số ba; ba người/ba vật; số 3", pronunciation: "/θriː/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "249", english: "Four", mean: "Bốn; số bốn; bốn người/bốn vật; số 4", pronunciation: "/fɔːr/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "250", english: "Five", mean: "Năm; số năm; năm người/năm vật; số 5; đập tay", pronunciation: "/faɪv/", partOfSpeech: "Number / Noun / Adjective / Verb" },
    { index: "251", english: "Six", mean: "Sáu; số sáu; sáu người/sáu vật; số 6", pronunciation: "/sɪks/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "252", english: "Seven", mean: "Bảy; số bảy; bảy người/bảy vật; số 7", pronunciation: "/ˈsevən/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "253", english: "Eight", mean: "Tám; số tám; tám người/tám vật; số 8", pronunciation: "/eɪt/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "254", english: "Nine", mean: "Chín; số chín; chín người/chín vật; số 9", pronunciation: "/naɪn/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "255", english: "Ten", mean: "Mười; số mười; mười người/mười vật; số 10", pronunciation: "/ten/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "256", english: "Quiz", mean: "Bài kiểm tra; câu đố; kiểm tra kiến thức", pronunciation: "/kwɪz/", partOfSpeech: "Noun / Verb" },
    { index: "257", english: "Square", mean: "Hình vuông; quảng trường; ô vuông; vuông; bình phương; làm vuông; đối diện, thẳng góc", pronunciation: "/skwer/", partOfSpeech: "Noun / Adjective / Verb / Adverb" },
    { index: "258", english: "Note", mean: "Ghi chú; lời nhắn; lưu ý; nốt nhạc; tiền giấy; ghi chú, ghi lại; chú ý", pronunciation: "/noʊt/", partOfSpeech: "Noun / Verb" },
    { index: "259", english: "List", mean: "Danh sách; bảng liệt kê; danh mục; liệt kê; ghi vào danh sách", pronunciation: "/lɪst/", partOfSpeech: "Noun / Verb" },
    { index: "260", english: "Do", mean: "Làm; thực hiện; tiến hành; làm bài; giải quyết; đủ, vừa; tổ chức; công việc; nhiệm vụ; bữa tiệc", pronunciation: "/duː/", partOfSpeech: "Verb / Noun" },
    { index: "261", english: "Farm", mean: "Nông trại; trang trại; canh tác; nuôi trồng; giao khoán", pronunciation: "/fɑːrm/", partOfSpeech: "Noun / Verb" },
    { index: "262", english: "Box", mean: "Hộp; thùng; ô; khung; lồng; quyền anh; đánh quyền anh; đóng hộp; nhốt vào hộp", pronunciation: "/bɒks/", partOfSpeech: "Noun / Verb" },
    { index: "263", english: "Ox", mean: "Con bò đực; bò kéo", pronunciation: "/ɒks/", partOfSpeech: "Noun" },
    { index: "264", english: "Fox", mean: "Con cáo; người xảo quyệt; cáo (động từ); đánh lừa, làm bối rối", pronunciation: "/fɒks/", partOfSpeech: "Noun / Verb" },
    { index: "265", english: "Rear", mean: "Phía sau; phần sau; hậu phương; nuôi dưỡng; nuôi lớn; dựng đứng; phía sau", pronunciation: "/rɪr/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "266", english: "Range", mean: "Phạm vi; khoảng; dãy; hàng loạt; tầm bắn; tầm hoạt động; phạm vi giá; bếp nấu; dao động, trải rộng", pronunciation: "/reɪndʒ/", partOfSpeech: "Noun / Verb" },
    { index: "267", english: "Rearrange", mean: "Sắp xếp lại; bố trí lại; thay đổi thứ tự; điều chỉnh lại", pronunciation: "/ˌriːəˈreɪndʒ/", partOfSpeech: "Verb" },
    { index: "268", english: "Guess", mean: "Đoán; phỏng đoán; cho rằng; sự đoán; câu trả lời phỏng đoán", pronunciation: "/ɡes/", partOfSpeech: "Verb / Noun" },
    { index: "269", english: "Kitchen", mean: "Nhà bếp; phòng bếp", pronunciation: "/ˈkɪtʃən/", partOfSpeech: "Noun" },
    { index: "270", english: "Jelly", mean: "Thạch; mứt đông; chất mềm như thạch; làm thành thạch", pronunciation: "/ˈdʒeli/", partOfSpeech: "Noun / Verb" },
    { index: "271", english: "Juice", mean: "Nước ép; nước quả; dịch, nước từ thực phẩm; năng lượng, sức mạnh; ép lấy nước", pronunciation: "/dʒuːs/", partOfSpeech: "Noun / Verb" },
    { index: "272", english: "Jam", mean: "Mứt; sự kẹt, tắc nghẽn; buổi chơi nhạc ngẫu hứng; nhét chặt; làm kẹt; gây nhiễu sóng", pronunciation: "/dʒæm/", partOfSpeech: "Noun / Verb" },
    { index: "273", english: "Pass", mean: "Đi qua; vượt qua; chuyền; đưa; đỗ, vượt qua kỳ thi; bỏ qua; qua đời; giấy phép; đường đèo; sự chuyền bóng; sự vượt qua", pronunciation: "/pɑːs/", partOfSpeech: "Verb / Noun" },
    { index: "274", english: "Pass me", mean: "Đưa cho tôi; chuyền cho tôi", pronunciation: "/pɑːs miː/", partOfSpeech: "Verb Phrase" },
    { index: "275", english: "Village", mean: "Làng; ngôi làng; cộng đồng làng", pronunciation: "/ˈvɪlɪdʒ/", partOfSpeech: "Noun" },
    { index: "276", english: "Van", mean: "Xe tải nhỏ; xe van; xe chở hàng; người tiên phong, người dẫn đầu", pronunciation: "/væn/", partOfSpeech: "Noun" },
    { index: "277", english: "Volleyball", mean: "Bóng chuyền; quả bóng chuyền", pronunciation: "/ˈvɒlibɔːl/", partOfSpeech: "Noun" },
    { index: "278", english: "Again", mean: "Lại; lại một lần nữa; thêm lần nữa; trở lại; ngoài ra; hơn nữa", pronunciation: "/əˈɡen/", partOfSpeech: "Adverb" },
    { index: "279", english: "Grocery", mean: "Hàng tạp hóa; thực phẩm và đồ dùng gia đình; cửa hàng tạp hóa", pronunciation: "/ˈɡroʊsəri/", partOfSpeech: "Noun" },
    { index: "280", english: "Corner", mean: "Góc; góc đường; góc phòng; nơi khuất; tình thế khó khăn; độc quyền thị trường; dồn vào góc; ép vào thế bí", pronunciation: "/ˈkɔːrnər/", partOfSpeech: "Noun / Verb" },
    { index: "281", english: "Yogurt", mean: "Sữa chua", pronunciation: "/ˈjoʊɡərt/", partOfSpeech: "Noun" },
    { index: "282", english: "Yam", mean: "Củ từ; khoai mỡ; một số loại củ giàu tinh bột", pronunciation: "/jæm/", partOfSpeech: "Noun" },
    { index: "283", english: "Yo-yo", mean: "Đồ chơi yo-yo; lên xuống thất thường; dao động lên xuống", pronunciation: "/ˈjoʊjoʊ/", partOfSpeech: "Noun / Verb / Adjective" },
    { index: "284", english: "Whisper", mean: "Thì thầm; nói nhỏ; tiếng thì thầm; lời nói nhỏ", pronunciation: "/ˈwɪspər/", partOfSpeech: "Verb / Noun" },
    { index: "285", english: "Want", mean: "Muốn; mong muốn; cần; thiếu; sự thiếu thốn; nhu cầu", pronunciation: "/wɒnt/", partOfSpeech: "Verb / Noun" },
    { index: "286", english: "Some", mean: "Một vài; một số; một ít; một lượng nào đó; khoảng; vài; một số người/vật; khá, tương đối", pronunciation: "/sʌm/", partOfSpeech: "Determiner / Pronoun / Adverb" },
    { index: "287", english: "Mum", mean: "Mẹ; hoa cúc; im lặng, không nói gì", pronunciation: "/mʌm/", partOfSpeech: "Noun / Adjective" },
    { index: "288", english: "Zebra", mean: "Ngựa vằn", pronunciation: "/ˈziːbrə/", partOfSpeech: "Noun" },
    { index: "289", english: "Zebu", mean: "Bò u; bò Zebu", pronunciation: "/ˈziːbuː/", partOfSpeech: "Noun" },
    { index: "290", english: "Good", mean: "Tốt; tốt đẹp; giỏi; khỏe; phù hợp; có ích; tử tế; tốt lành; điều tốt; lợi ích; hàng hóa; điều thiện", pronunciation: "/ɡʊd/", partOfSpeech: "Adjective / Noun / Adverb" },
    { index: "291", english: "Job", mean: "Công việc; việc làm; nhiệm vụ; công việc cụ thể; nghề nghiệp; việc khó; làm việc, làm thuê", pronunciation: "/dʒɒb/", partOfSpeech: "Noun / Verb" },
    { index: "292", english: "Goodjob", mean: "Làm tốt lắm; làm tốt; công việc tốt", pronunciation: "/ɡʊd dʒɒb/", partOfSpeech: "Phrase / Noun" },
    { index: "293", english: "Drive", mean: "Lái xe; điều khiển; thúc đẩy; đưa đi bằng xe; lái xe; ổ đĩa; chuyến đi bằng xe; động lực; sự thôi thúc; đường xe chạy; cú đánh (golf/tennis)", pronunciation: "/draɪv/", partOfSpeech: "Verb / Noun" },
    { index: "294", english: "Slide", mean: "Trượt; trượt xuống; trượt qua; cầu trượt; sự trượt; trang chiếu; nắp trượt; lam kính; trượt nhẹ nhàng", pronunciation: "/slaɪd/", partOfSpeech: "Verb / Noun" },
    { index: "295", english: "They", mean: "Họ; chúng; họ/những người đó; người ta; một người (khi không xác định giới tính)", pronunciation: "/ðeɪ/", partOfSpeech: "Pronoun" },
    { index: "296", english: "Table", mean: "Cái bàn; bảng; bảng biểu; bảng danh sách; bàn ăn; lập bảng; trình bày dưới dạng bảng; hoãn việc thảo luận (Anh-Anh)", pronunciation: "/ˈteɪbəl/", partOfSpeech: "Noun / Verb" },
    { index: "297", english: "Grape", mean: "Quả nho; cây nho; chùm nho", pronunciation: "/ɡreɪp/", partOfSpeech: "Noun" },
    { index: "298", english: "Ask", mean: "Hỏi; yêu cầu; đề nghị; xin; mời; đòi hỏi; hỏi giá; yêu cầu ai làm gì", pronunciation: "/ɑːsk/", partOfSpeech: "Verb / Noun" },
    { index: "299", english: "Friend", mean: "Bạn; bạn bè; người ủng hộ; người có cùng sở thích; làm bạn với", pronunciation: "/frend/", partOfSpeech: "Noun / Verb" },
    { index: "300", english: "Friendly", mean: "Thân thiện; hòa nhã; thân mật; hữu nghị; thân thiện với; không mang tính thù địch", pronunciation: "/ˈfrendli/", partOfSpeech: "Adjective / Adverb" },
    { index: "301", english: "Too", mean: "Cũng; quá; quá mức; rất, cực kỳ (thân mật); ngoài ra", pronunciation: "/tuː/", partOfSpeech: "Adverb" },
    { index: "302", english: "Math", mean: "Toán học; môn toán; phép tính", pronunciation: "/mæθ/", partOfSpeech: "Noun" },
    { index: "303", english: "Number", mean: "Số; con số; số lượng; số thứ tự; số điện thoại; đánh số; tính toán", pronunciation: "/ˈnʌmbər/", partOfSpeech: "Noun / Verb" },
    { index: "304", english: "Eleven", mean: "Mười một; số mười một; 11 người/vật", pronunciation: "/ɪˈlevən/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "305", english: "Twelve", mean: "Mười hai; số mười hai; 12 người/vật", pronunciation: "/twelv/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "306", english: "Thirteen", mean: "Mười ba; số mười ba; 13 người/vật", pronunciation: "/ˌθɜːrˈtiːn/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "307", english: "Fourteen", mean: "Mười bốn; số mười bốn; 14 người/vật", pronunciation: "/ˌfɔːrˈtiːn/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "308", english: "Fifteen", mean: "Mười lăm; số mười lăm; 15 người/vật", pronunciation: "/ˌfɪfˈtiːn/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "309", english: "Twenty", mean: "Hai mươi; số hai mươi; 20 người/vật", pronunciation: "/ˈtwenti/", partOfSpeech: "Number / Noun / Adjective" },
    { index: "310", english: "Race", mean: "Cuộc đua; cuộc chạy đua; chủng tộc; giống, loài; đua; chạy đua; cạnh tranh", pronunciation: "/reɪs/", partOfSpeech: "Noun / Verb" },
    { index: "311", english: "Start", mean: "Bắt đầu; khởi đầu; xuất phát; khởi động; điểm bắt đầu; sự khởi đầu; sự xuất phát", pronunciation: "/stɑːrt/", partOfSpeech: "Verb / Noun" },
    { index: "312", english: "Doll", mean: "Búp bê; người phụ nữ/cô gái (thân mật); ăn mặc đẹp", pronunciation: "/dɒl/", partOfSpeech: "Noun / Verb" },
    { index: "313", english: "Audio", mean: "Âm thanh; phần âm thanh; thuộc về âm thanh", pronunciation: "/ˈɔːdioʊ/", partOfSpeech: "Noun / Adjective" },
    { index: "314", english: "Script", mean: "Kịch bản; bản thảo; chữ viết; hệ chữ; văn bản; viết kịch bản; viết tay", pronunciation: "/skrɪpt/", partOfSpeech: "Noun / Verb" },
    { index: "315", english: "Dad", mean: "Bố; cha", pronunciation: "/dæd/", partOfSpeech: "Noun" },
    { index: "316", english: "Mom", mean: "Mẹ; má", pronunciation: "/mɑːm/", partOfSpeech: "Noun" },
    { index: "317", english: "Parent", mean: "Cha hoặc mẹ; phụ huynh; nguồn gốc; cha/mẹ của; làm cha mẹ", pronunciation: "/ˈperənt/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "318", english: "Grandparent", mean: "Ông hoặc bà; ông bà", pronunciation: "/ˈɡrænperənt/", partOfSpeech: "Noun" },
    { index: "319", english: "Grandmother", mean: "Bà; bà nội hoặc bà ngoại", pronunciation: "/ˈɡrænmʌðər/", partOfSpeech: "Noun" },
    { index: "320", english: "Grandfather", mean: "Ông; ông nội hoặc ông ngoại", pronunciation: "/ˈɡrænfɑːðər/", partOfSpeech: "Noun" },
    { index: "321", english: "Brother", mean: "Anh; em trai; anh/em ruột; người cùng nhóm/tổ chức", pronunciation: "/ˈbrʌðər/", partOfSpeech: "Noun" },
    { index: "322", english: "Sister", mean: "Chị; em gái; chị/em ruột; nữ tu; người phụ nữ cùng nhóm/tổ chức", pronunciation: "/ˈsɪstər/", partOfSpeech: "Noun" },
    { index: "323", english: "Young", mean: "Trẻ; trẻ tuổi; non; mới; thiếu kinh nghiệm; con non; người trẻ; tuổi trẻ", pronunciation: "/jʌŋ/", partOfSpeech: "Adjective / Noun" },
    { index: "324", english: "Old", mean: "Già; cũ; lâu đời; lâu; trước đây; lớn tuổi; quen thuộc; người già; bạn cũ", pronunciation: "/oʊld/", partOfSpeech: "Adjective / Noun" },
    { index: "325", english: "We", mean: "Chúng tôi; chúng ta; chúng mình", pronunciation: "/wiː/", partOfSpeech: "Pronoun" },
    { index: "326", english: "All", mean: "Tất cả; mọi; toàn bộ; mọi người; mọi thứ; hoàn toàn; hết, toàn bộ", pronunciation: "/ɔːl/", partOfSpeech: "Determiner / Pronoun / Adverb" },
    { index: "327", english: "Clothe", mean: "Mặc quần áo cho; cho mặc; che phủ", pronunciation: "/kloʊð/", partOfSpeech: "Verb" },
    { index: "328", english: "Shoe", mean: "Giày; móng guốc; đóng móng guốc; lắp/đặt lớp bảo vệ", pronunciation: "/ʃuː/", partOfSpeech: "Noun / Verb" },
    { index: "329", english: "Short", mean: "Ngắn; thấp; thiếu; không đủ; ngắn hạn; quần short; mạch điện ngắn; bán khống; làm ngắn", pronunciation: "/ʃɔːrt/", partOfSpeech: "Adjective / Noun / Adverb / Verb" },
    { index: "330", english: "Shorts", mean: "Quần đùi; quần short; phim ngắn; vị thế bán khống", pronunciation: "/ʃɔːrts/", partOfSpeech: "Noun" },
    { index: "331", english: "Shirt", mean: "Áo sơ mi; áo; mặc áo sơ mi", pronunciation: "/ʃɜːrt/", partOfSpeech: "Noun / Verb" },
    { index: "332", english: "Over", mean: "Trên; ở phía trên; qua; vượt qua; hơn; kết thúc; xong; lặp lại; quá mức", pronunciation: "/ˈoʊvər/", partOfSpeech: "Preposition / Adverb / Adjective" },
    { index: "333", english: "Over there", mean: "Ở đằng kia; ở phía bên kia; ở chỗ đó", pronunciation: "/ˈoʊvər ðer/", partOfSpeech: "Adverbial Phrase" },
    { index: "334", english: "Camp", mean: "Trại; khu cắm trại; cắm trại; đóng trại; phe, nhóm", pronunciation: "/kæmp/", partOfSpeech: "Noun / Verb" },
    { index: "335", english: "Site", mean: "Địa điểm; vị trí; khu đất; địa điểm xây dựng; trang web; đặt ở một vị trí", pronunciation: "/saɪt/", partOfSpeech: "Noun / Verb" },
    { index: "336", english: "Campsite", mean: "Khu cắm trại; địa điểm cắm trại", pronunciation: "/ˈkæmpsaɪt/", partOfSpeech: "Noun" },
    { index: "337", english: "Tent", mean: "Lều; căng lều; sống trong lều", pronunciation: "/tent/", partOfSpeech: "Noun / Verb" },
    { index: "338", english: "Teapot", mean: "Ấm pha trà; bình trà", pronunciation: "/ˈtiːpɒt/", partOfSpeech: "Noun" },
    { index: "339", english: "Blanket", mean: "Chăn; mền; lớp phủ; bao phủ hoàn toàn; phủ kín", pronunciation: "/ˈblæŋkɪt/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "340", english: "Fence", mean: "Hàng rào; rào lại; bảo vệ; tránh né; mua bán hàng hóa bất hợp pháp", pronunciation: "/fens/", partOfSpeech: "Noun / Verb" },
    { index: "341", english: "Nice", mean: "Tốt; đẹp; dễ chịu; thân thiện; tử tế; chính xác; tinh tế; hay, thú vị", pronunciation: "/naɪs/", partOfSpeech: "Adjective" },
    { index: "342", english: "Luck", mean: "May mắn; vận may; sự may rủi; cơ hội", pronunciation: "/lʌk/", partOfSpeech: "Noun" },
    { index: "343", english: "Trip", mean: "Chuyến đi; chuyến du lịch; sự vấp ngã; bước hụt; vấp; làm vấp; kích hoạt, làm khởi động", pronunciation: "/trɪp/", partOfSpeech: "Noun / Verb" },
    { index: "344", english: "Delicious", mean: "Ngon; thơm ngon; rất thú vị, hấp dẫn", pronunciation: "/dɪˈlɪʃəs/", partOfSpeech: "Adjective" },
    { index: "345", english: "Stay", mean: "Ở lại; lưu trú; tiếp tục; trì hoãn; ở, lưu trú; sự ở lại; thời gian lưu trú; sự trì hoãn", pronunciation: "/steɪ/", partOfSpeech: "Verb / Noun" },
    { index: "346", english: "Family", mean: "Gia đình; họ hàng; gia tộc; dòng họ; nhóm có quan hệ; họ, dòng (sinh học); thuộc về gia đình", pronunciation: "/ˈfæməli/", partOfSpeech: "Noun / Adjective" },
    { index: "347", english: "New", mean: "Mới; mới mẻ; chưa từng dùng; gần đây; khác biệt; mới đến; người mới", pronunciation: "/njuː/", partOfSpeech: "Adjective / Adverb / Noun" },
    { index: "348", english: "Hungry", mean: "Đói; đói bụng; khao khát; rất muốn", pronunciation: "/ˈhʌŋɡri/", partOfSpeech: "Adjective" },
    { index: "349", english: "Now", mean: "Bây giờ; hiện nay; lúc này; ngay lập tức; vậy thì; hiện tại", pronunciation: "/naʊ/", partOfSpeech: "Adverb / Noun / Adjective / Conjunction" },
    { index: "350", english: "Picnic", mean: "Buổi dã ngoại; chuyến đi dã ngoại; đi dã ngoại", pronunciation: "/ˈpɪknɪk/", partOfSpeech: "Noun / Verb" },
    { index: "351", english: "Story", mean: "Câu chuyện; truyện; câu chuyện kể; tin tức; lời giải thích; tầng của tòa nhà (Mỹ)", pronunciation: "/ˈstɔːri/", partOfSpeech: "Noun" },
    { index: "352", english: "Each", mean: "Mỗi; mỗi người; mỗi cái; từng", pronunciation: "/iːtʃ/", partOfSpeech: "Determiner / Pronoun / Adverb" },
    { index: "353", english: "From", mean: "Từ; từ...đến; bắt nguồn từ; kể từ; do; bởi; cách xa; không có", pronunciation: "/frəm/", partOfSpeech: "Preposition" },
    { index: "354", english: "Text", mean: "Văn bản; bài viết; nội dung; tin nhắn; nhắn tin; gửi tin nhắn", pronunciation: "/tekst/", partOfSpeech: "Noun / Verb" },
    { index: "355", english: "Test", mean: "Bài kiểm tra; cuộc kiểm tra; xét nghiệm; thử nghiệm; kiểm tra; thử; xét nghiệm", pronunciation: "/test/", partOfSpeech: "Noun / Verb" },
    { index: "356", english: "Pond", mean: "Ao; hồ nhỏ; vùng nước nhỏ", pronunciation: "/pɒnd/", partOfSpeech: "Noun" },
    // Class 3
    { index: "357", english: "Hello", mean: "Xin chào; lời chào; này, alo; tiếng gọi để thu hút sự chú ý", pronunciation: "/həˈloʊ/", partOfSpeech: "Interjection / Noun / Verb" },
    { index: "358", english: "Hi", mean: "Xin chào; chào", pronunciation: "/haɪ/", partOfSpeech: "Interjection" },
    { index: "359", english: "I", mean: "Tôi; mình; tôi (đại từ nhân xưng ngôi thứ nhất số ít)", pronunciation: "/aɪ/", partOfSpeech: "Pronoun" },
    { index: "360", english: "You", mean: "Bạn; bạn (số ít); các bạn; các bạn (số nhiều); anh; chị; ông; bà; mày; cậu", pronunciation: "/juː/", partOfSpeech: "Pronoun" },
    { index: "361", english: "Complete", mean: "Hoàn thành; hoàn tất; đầy đủ; hoàn chỉnh; trọn vẹn; hoàn toàn; hoàn thành một việc", pronunciation: "/kəmˈpliːt/", partOfSpeech: "Verb / Adjective" },
    { index: "362", english: "Fine", mean: "Tốt; ổn; khỏe; tốt đẹp; mịn; nhỏ; tinh tế; tiền phạt; tiền phạt; phạt tiền; làm mịn", pronunciation: "/faɪn/", partOfSpeech: "Adjective / Noun / Verb / Adverb" },
    { index: "363", english: "Pupil", mean: "Học sinh; đồng tử (mắt)", pronunciation: "/ˈpjuːpəl/", partOfSpeech: "Noun" },
    { index: "364", english: "Card", mean: "Thẻ; thiệp; quân bài; danh thiếp; thẻ tín dụng; người kỳ quặc/hài hước; ghi vào thẻ; làm thiệp", pronunciation: "/kɑːrd/", partOfSpeech: "Noun / Verb" },
    { index: "365", english: "Pupil card", mean: "Thẻ học sinh; thẻ học viên", pronunciation: "/ˈpjuːpəl kɑːrd/", partOfSpeech: "Noun" },
    { index: "366", english: "Project", mean: "Dự án; đề án; bài tập/dự án học tập; dự kiến; dự đoán; chiếu; phóng; nhô ra", pronunciation: "/ˈprɒdʒekt/; /prəˈdʒekt/", partOfSpeech: "Noun / Verb" },
    { index: "367", english: "Our", mean: "Của chúng tôi; của chúng ta; của chúng mình", pronunciation: "/aʊər/", partOfSpeech: "Determiner" },
    { index: "368", english: "Name", mean: "Tên; tên gọi; danh tiếng; người nổi tiếng; tên tuổi; đặt tên; gọi tên; chỉ định", pronunciation: "/neɪm/", partOfSpeech: "Noun / Verb" },
    { index: "369", english: "Track", mean: "Đường mòn; đường ray; đường chạy; bài hát; dấu vết; theo dõi; truy tìm; đi theo", pronunciation: "/træk/", partOfSpeech: "Noun / Verb" },
    { index: "370", english: "Bill", mean: "Hóa đơn; dự luật; tờ tiền; danh sách món ăn; mỏ chim; lập hóa đơn; tính tiền; quảng cáo, áp phích", pronunciation: "/bɪl/", partOfSpeech: "Noun / Verb" },
    { index: "371", english: "Mr", mean: "Ông; ngài; ngài/ông (cách xưng hô lịch sự với nam giới)", pronunciation: "/ˈmɪstər/", partOfSpeech: "Title / Noun" },
    { index: "372", english: "Ms", mean: "Bà; cô; chị (cách xưng hô lịch sự với phụ nữ, không nêu tình trạng hôn nhân)", pronunciation: "/mɪz/", partOfSpeech: "Title / Noun" },
    { index: "373", english: "Teach", mean: "Dạy; giảng dạy; chỉ dẫn; truyền đạt kiến thức", pronunciation: "/tiːtʃ/", partOfSpeech: "Verb" },
    { index: "374", english: "Teacher", mean: "Giáo viên; giáo viên nam; giáo viên nữ; người dạy học; người hướng dẫn", pronunciation: "/ˈtiːtʃər/", partOfSpeech: "Noun" },
    { index: "375", english: "Brown", mean: "Màu nâu; nâu; có màu nâu; làm cho chuyển sang màu nâu", pronunciation: "/braʊn/", partOfSpeech: "Adjective / Noun / Verb" },
    { index: "376", english: "Blue", mean: "Màu xanh dương; màu xanh lam; buồn; buồn bã; xanh dương/xanh lam; nhạc blues", pronunciation: "/bluː/", partOfSpeech: "Adjective / Noun / Verb" },
    { index: "377", english: "Sky blue", mean: "Xanh da trời; xanh thiên thanh", pronunciation: "/ˌskaɪ ˈbluː/", partOfSpeech: "Adjective / Noun" },
    { index: "378", english: "Green", mean: "Màu xanh lá cây; xanh lục; còn non; chưa chín; thiếu kinh nghiệm; thân thiện với môi trường; cây xanh; màu xanh; làm cho xanh; làm cho xanh tươi", pronunciation: "/ɡriːn/", partOfSpeech: "Adjective / Noun / Verb" },
    { index: "379", english: "Black", mean: "Màu đen; đen; tối tăm; u ám; người da đen; màu đen; làm cho đen; bôi đen; tẩy chay", pronunciation: "/blæk/", partOfSpeech: "Adjective / Noun / Verb" },
    { index: "380", english: "Yellow", mean: "Màu vàng; vàng; nhút nhát; hèn nhát; màu vàng; trở nên vàng; làm cho vàng", pronunciation: "/ˈjeləʊ/", partOfSpeech: "Adjective / Noun / Verb" },
    { index: "381", english: "Purple", mean: "Màu tím; tím; có màu tím; làm cho có màu tím", pronunciation: "/ˈpɜːrpəl/", partOfSpeech: "Adjective / Noun / Verb" },
    { index: "382", english: "Violet", mean: "Màu tím violet; tím xanh; hoa violet; cây violet", pronunciation: "/ˈvaɪələt/", partOfSpeech: "Adjective / Noun" },
    { index: "383", english: "Pink", mean: "Màu hồng; hồng; có màu hồng; màu hồng; hoa cẩm chướng; đâm/chọc bằng vật nhọn; làm thủng; kêu réo/rít", pronunciation: "/pɪŋk/", partOfSpeech: "Adjective / Noun / Verb" },
    { index: "384", english: "White", mean: "Màu trắng; trắng; nhợt nhạt; tóc bạc; người da trắng; màu trắng; lòng trắng trứng; làm trắng; tẩy trắng", pronunciation: "/waɪt/", partOfSpeech: "Adjective / Noun / Verb" },
    { index: "385", english: "Grey", mean: "Màu xám; xám; bạc màu; tóc bạc; u ám; buồn tẻ", pronunciation: "/ɡreɪ/", partOfSpeech: "Adjective / Noun / Verb" },
    { index: "386", english: "Image", mean: "Hình ảnh; hình; ảnh; hình tượng; hình ảnh trong tâm trí; hình tượng/ấn tượng về một người hoặc vật; hình ảnh phản chiếu; tạo hình ảnh; hình dung", pronunciation: "/ˈɪmɪdʒ/", partOfSpeech: "Noun / Verb" },
    { index: "387", english: "Phone", mean: "Điện thoại; điện thoại di động; cuộc gọi điện thoại; gọi điện thoại; gọi cho ai", pronunciation: "/fəʊn/", partOfSpeech: "Noun / Verb" },
    { index: "388", english: "Phonetic", mean: "Thuộc về ngữ âm; thuộc về âm thanh lời nói; phiên âm; dùng để biểu thị âm thanh", pronunciation: "/fəˈnetɪk/", partOfSpeech: "Adjective" },
    { index: "389", english: "Mean", mean: "Có nghĩa là; có ý nghĩa; muốn nói; có ý định; có nghĩa; ám chỉ; dự định; keo kiệt; xấu tính; trung bình; giá trị trung bình; mức trung bình", pronunciation: "/miːn/", partOfSpeech: "Verb / Adjective / Noun" },
    { index: "390", english: "No", mean: "Không; không phải; không có; không được; không đồng ý; không (dùng để trả lời phủ định); số không; không một chút nào", pronunciation: "/nəʊ/", partOfSpeech: "Adverb / Determiner / Pronoun / Noun" },
    { index: "391", english: "Yes", mean: "Có; vâng; dạ; đúng; đồng ý; lời đồng ý; lời chấp thuận", pronunciation: "/jes/", partOfSpeech: "Adverb / Noun" },
    { index: "392", english: "Best", mean: "Tốt nhất; giỏi nhất; đẹp nhất; phù hợp nhất; tốt nhất có thể; điều tốt nhất; người tốt nhất; phần tốt nhất; hết sức; tốt nhất; vượt qua; đánh bại", pronunciation: "/best/", partOfSpeech: "Adjective / Adverb / Noun / Verb" },
    { index: "393", english: "Best friend", mean: "Bạn thân nhất; người bạn thân nhất", pronunciation: "/ˌbest ˈfrend/", partOfSpeech: "Noun" },
    { index: "394", english: "Close", mean: "Gần; gần gũi; thân thiết; kín; đóng; kết thúc; khép lại; đóng cửa; chấm dứt; kết thúc; sát; chặt chẽ; gần như; trong thời gian ngắn; sự đóng cửa; sự kết thúc", pronunciation: "/kləʊz/; /kləʊs/", partOfSpeech: "Adjective / Adverb / Verb / Noun" },
    { index: "395", english: "Close friend", mean: "Bạn thân; người bạn thân thiết", pronunciation: "/ˌkləʊs ˈfrend/", partOfSpeech: "Noun" },
    { index: "396", english: "Body", mean: "Cơ thể; thân thể; thân người; phần thân của người hoặc động vật; xác chết; thân xe; thân tàu; nhóm người/tổ chức; khối lượng; phần chính của một vật; nội dung chính; thân bài; độ đậm/đầy của đồ uống; có thân hình; tạo hình/thành khối", pronunciation: "/ˈbɒdi/", partOfSpeech: "Noun / Verb" },
    { index: "397", english: "Open", mean: "Mở; mở ra; mở cửa; khai trương; bắt đầu; cởi mở; công khai; chưa đóng; trống; đang hoạt động; mở rộng; mở lòng; sự mở cửa; khoảng trống; ngoài trời; mở/khai mở", pronunciation: "/ˈəʊpən/", partOfSpeech: "Adjective / Verb / Noun" },
    { index: "398", english: "Part", mean: "Phần; bộ phận; một phần; phần nào; vai trò; nhân vật; bộ phận máy móc; phụ tùng; khu vực; phe/phía; phần việc; chia phần; tách ra; rời đi; chia tay; tham gia một phần; một phần của tổng thể", pronunciation: "/pɑːt/", partOfSpeech: "Noun / Verb / Adjective / Adverb" },
    { index: "399", english: "Ear", mean: "Tai; cơ quan thính giác; khả năng nghe/cảm âm; sự chú ý đến âm thanh; bắp/ngô (một bông hoặc cụm hạt ngũ cốc)", pronunciation: "/ɪə(r)/", partOfSpeech: "Noun" },
    { index: "400", english: "Eye", mean: "Mắt; con mắt; thị lực; khả năng quan sát; ánh nhìn; sự chú ý; lỗ/mắt của kim; mắt của bão; nút/mắt (trên khoai tây); nhìn; quan sát; để mắt đến", pronunciation: "/aɪ/", partOfSpeech: "Noun / Verb" },
    { index: "401", english: "Nose", mean: "Mũi; khứu giác; phần mũi/phần nhô ra phía trước; mũi của máy bay/tàu; đánh hơi; ngửi; dò tìm; can thiệp vào chuyện người khác", pronunciation: "/nəʊz/", partOfSpeech: "Noun / Verb" },
    { index: "402", english: "Mouth", mean: "Miệng; khoang miệng; cửa sông; miệng hang; miệng chai/lọ; lời nói; phát ngôn; nói; phát âm; nói ra; nhép miệng; dùng miệng để đưa vào", pronunciation: "/maʊθ/", partOfSpeech: "Noun / Verb" },

];