/*******************************
 * 1) DỮ LIỆU TỪ VỰNG (ví dụ)
 * Thay/ví dụ bằng 1000 từ của bạn.
 *******************************/
// noun
// pronoun
// verb
// adjective
// adverb
// preposition
// conjunction
// interjection
const vocabularyList = [
    //    // { index: "", english: "", mean: "", pronunciation: "", partOfSpeech: "" },
    { index: "1", english: "tea", mean: "trà", pronunciation: "UK: /tiː/ | US: /tiː/", partOfSpeech: "noun" },
    { index: "2", english: "coffee", mean: "cà phê", pronunciation: "UK: /ˈkɒfi/ | US: /ˈkɔːfi/", partOfSpeech: "noun" },
    { index: "3", english: "welcome", mean: "chào mừng", pronunciation: "UK: /ˈwelkəm/ | US: /ˈwelkəm/", partOfSpeech: "verb, adjective, interjection" },
    { index: "4", english: "please", mean: "vui lòng, làm ơn", pronunciation: "UK: /pliːz/ | US: /pliːz/", partOfSpeech: "interjection, verb" },
    { index: "5", english: "or", mean: "hoặc", pronunciation: "UK: /ɔː/ | US: /ɔːr/", partOfSpeech: "conjunction" },
    { index: "6", english: "sugar", mean: "đường", pronunciation: "UK: /ˈʃʊɡə/ | US: /ˈʃʊɡər/", partOfSpeech: "noun" },
    { index: "7", english: "milk", mean: "sữa", pronunciation: "UK: /mɪlk/ | US: /mɪlk/", partOfSpeech: "noun" },
    { index: "8", english: "with", mean: "với", pronunciation: "UK: /wɪð/ | US: /wɪð/", partOfSpeech: "preposition" },
    { index: "9", english: "water", mean: "nước", pronunciation: "UK: /ˈwɔːtə/ | US: /ˈwɔːtər/", partOfSpeech: "noun" },
    { index: "10", english: "goodbye", mean: "tạm biệt", pronunciation: "UK: /ˌɡʊdˈbaɪ/ | US: /ˌɡʊdˈbaɪ/", partOfSpeech: "interjection, noun" },
    { index: "11", english: "and", mean: "và", pronunciation: "UK: /ænd/ | US: /ænd/", partOfSpeech: "conjunction" },
    { index: "12", english: "thank you", mean: "cảm ơn", pronunciation: "UK: /ˈθæŋk juː/ | US: /ˈθæŋk juː/", partOfSpeech: "interjection" },
    { index: "13", english: "Ball", mean: "Quả bóng", pronunciation: "/bɔːl/", partOfSpeech: "Noun" },
    { index: "14", english: "Bike", mean: "Xe đạp", pronunciation: "/baɪk/", partOfSpeech: "Noun" },
    { index: "15", english: "Book", mean: "Sách", pronunciation: "/bʊk/", partOfSpeech: "Noun" },
    { index: "16", english: "School", mean: "Trường học", pronunciation: "/skuːl/", partOfSpeech: "Noun" },
    { index: "17", english: "Play", mean: "Chơi", pronunciation: "/pleɪ/", partOfSpeech: "Verb" },
    { index: "18", english: "Ground", mean: "Mặt đất", pronunciation: "/ɡraʊnd/", partOfSpeech: "Noun" },
    { index: "19", english: "Playground", mean: "Sân chơi", pronunciation: "/ˈpleɪɡraʊnd/", partOfSpeech: "Noun" },
    { index: "20", english: "Listen", mean: "Lắng nghe", pronunciation: "/ˈlɪsən/", partOfSpeech: "Verb" },
    { index: "21", english: "Repeat", mean: "Lặp lại", pronunciation: "/rɪˈpiːt/", partOfSpeech: "Verb" },
    { index: "22", english: "In", mean: "Trong", pronunciation: "/ɪn/", partOfSpeech: "Preposition" },
    { index: "23", english: "Point", mean: "Điểm; chỉ vào", pronunciation: "/pɔɪnt/", partOfSpeech: "Noun / Verb" },
    { index: "24", english: "Say", mean: "Nói", pronunciation: "/seɪ/", partOfSpeech: "Verb" },
    { index: "25", english: "Lesson", mean: "Bài học", pronunciation: "/ˈlesən/", partOfSpeech: "Noun" },
    { index: "26", english: "Unit", mean: "Đơn vị; bài học", pronunciation: "/ˈjuːnɪt/", partOfSpeech: "Noun" },
    { index: "27", english: "Let", mean: "Cho phép; để", pronunciation: "/let/", partOfSpeech: "Verb" },
    { index: "28", english: "Talk", mean: "Nói chuyện", pronunciation: "/tɔːk/", partOfSpeech: "Verb" },
    { index: "29", english: "Sing", mean: "Hát", pronunciation: "/sɪŋ/", partOfSpeech: "Verb" },
    { index: "30", english: "Chant", mean: "Hô; hát theo nhịp, tụng kinh", pronunciation: "/tʃɑːnt/", partOfSpeech: "Verb / Noun" },
    { index: "31", english: "Tick", mean: "Đánh dấu ✓; tích", pronunciation: "/tɪk/", partOfSpeech: "Verb / Noun" },
    { index: "32", english: "Look", mean: "Nhìn", pronunciation: "/lʊk/", partOfSpeech: "Verb" },
    { index: "33", english: "Trace", mean: "Đồ theo; lần theo dấu vết, theo dõi", pronunciation: "/treɪs/", partOfSpeech: "Verb / Noun" },
    { index: "34", english: "Room", mean: "Phòng; không gian", pronunciation: "/ruːm/", partOfSpeech: "Noun" },
    { index: "35", english: "Dining", mean: "Ăn uống; dùng bữa", pronunciation: "/ˈdaɪnɪŋ/", partOfSpeech: "Noun / Adjective" },
    { index: "36", english: "Dining room", mean: "Phòng ăn", pronunciation: "/ˈdaɪnɪŋ ruːm/", partOfSpeech: "Noun" },
    { index: "37", english: "Extra", mean: "Thêm; bổ sung; dư", pronunciation: "/ˈekstrə/", partOfSpeech: "Adjective / Noun" },
    { index: "38", english: "Resource", mean: "Tài nguyên; nguồn lực", pronunciation: "/rɪˈsɔːrs/", partOfSpeech: "Noun" },
    { index: "39", english: "Glossary", mean: "Bảng chú giải; danh mục từ, bảng thuật ngữ", pronunciation: "/ˈɡlɒsəri/", partOfSpeech: "Noun" },
    { index: "40", english: "Cup", mean: "Cốc; tách", pronunciation: "/kʌp/", partOfSpeech: "Noun" },
    { index: "41", english: "Car", mean: "Xe hơi; ô tô", pronunciation: "/kɑːr/", partOfSpeech: "Noun" },
    { index: "42", english: "Cat", mean: "Con mèo", pronunciation: "/kæt/", partOfSpeech: "Noun" },
    { index: "43", english: "Cake", mean: "Bánh ngọt; bánh", pronunciation: "/keɪk/", partOfSpeech: "Noun" },
    { index: "44", english: "Load", mean: "Tải; chất hàng", pronunciation: "/ləʊd/", partOfSpeech: "Verb / Noun" },
    { index: "45", english: "Loading", mean: "Đang tải", pronunciation: "/ˈləʊdɪŋ/", partOfSpeech: "Noun / Adjective" },
    { index: "46", english: "Fun", mean: "Vui vẻ; niềm vui", pronunciation: "/fʌn/", partOfSpeech: "Noun / Adjective" },
    { index: "47", english: "Time", mean: "Thời gian; lần", pronunciation: "/taɪm/", partOfSpeech: "Noun" },
    { index: "48", english: "Find", mean: "Tìm; tìm thấy", pronunciation: "/faɪnd/", partOfSpeech: "Verb" },
    { index: "49", english: "Circle", mean: "Khoanh tròn; hình tròn", pronunciation: "/ˈsɜːrkəl/", partOfSpeech: "Verb / Noun" },
    { index: "50", english: "Then", mean: "Sau đó; rồi", pronunciation: "/ðen/", partOfSpeech: "Adverb" },
    { index: "51", english: "Color", mean: "Màu sắc; tô màu", pronunciation: "/ˈkʌlər/", partOfSpeech: "Noun / Verb" },
    { index: "52", english: "Colour", mean: "Màu sắc; tô màu", pronunciation: "/ˈkʌlər/", partOfSpeech: "Noun / Verb" },
    { index: "53", english: "Activity", mean: "Hoạt động", pronunciation: "/ækˈtɪvəti/", partOfSpeech: "Noun" },
    { index: "54", english: "Level", mean: "Cấp độ; mức độ; tầng", pronunciation: "/ˈlevəl/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "55", english: "Little", mean: "Nhỏ; ít", pronunciation: "/ˈlɪtəl/", partOfSpeech: "Adjective / Adverb / Determiner" },
    { index: "56", english: "Big", mean: "To; lớn", pronunciation: "/bɪɡ/", partOfSpeech: "Adjective" },
    { index: "57", english: "Show", mean: "Cho xem; trình diễn", pronunciation: "/ʃəʊ/", partOfSpeech: "Verb / Noun" },
    { index: "58", english: "Happy", mean: "Vui vẻ; hạnh phúc", pronunciation: "/ˈhæpi/", partOfSpeech: "Adjective" },
    { index: "59", english: "Street", mean: "Đường phố", pronunciation: "/striːt/", partOfSpeech: "Noun" },
    { index: "60", english: "Market", mean: "Chợ; thị trường", pronunciation: "/ˈmɑːrkɪt/", partOfSpeech: "Noun" },
    { index: "61", english: "Global", mean: "Toàn cầu", pronunciation: "/ˈɡləʊbəl/", partOfSpeech: "Adjective" },
    { index: "62", english: "Success", mean: "Thành công", pronunciation: "/səkˈses/", partOfSpeech: "Noun" },
    { index: "63", english: "Hat", mean: "Mũ; nón", pronunciation: "/hæt/", partOfSpeech: "Noun" },
    { index: "64", english: "Apple", mean: "Quả táo", pronunciation: "/ˈæpəl/", partOfSpeech: "Noun" },
    { index: "65", english: "Can", mean: "Có thể; có khả năng; được phép; lon; hộp; đóng hộp", pronunciation: "/kæn/", partOfSpeech: "Modal Verb / Noun / Verb" },
    { index: "66", english: "Bag", mean: "Túi; cặp", pronunciation: "/bæɡ/", partOfSpeech: "Noun" },
    { index: "67", english: "On", mean: "Trên; ở trên", pronunciation: "/ɒn/", partOfSpeech: "Preposition / Adverb" },
    { index: "68", english: "There", mean: "Ở đó; kia", pronunciation: "/ðer/", partOfSpeech: "Adverb" },
    { index: "69", english: "This", mean: "Này; cái này", pronunciation: "/ðɪs/", partOfSpeech: "Determiner / Pronoun" },
    { index: "70", english: "Those", mean: "Những cái đó; những người đó", pronunciation: "/ðəʊz/", partOfSpeech: "Determiner / Pronoun" },
    { index: "71", english: "Orange", mean: "Quả cam; màu cam", pronunciation: "/ˈɒrɪndʒ/", partOfSpeech: "Noun / Adjective" },
    { index: "72", english: "Bed", mean: "Giường; luống (cây); đáy (sông, biển); lớp, tầng", pronunciation: "/bed/", partOfSpeech: "Noun / Verb" },
    { index: "73", english: "Bedroom", mean: "Phòng ngủ", pronunciation: "/ˈbedruːm/", partOfSpeech: "Noun" },
    { index: "74", english: "Door", mean: "Cửa; lối vào; cánh cửa", pronunciation: "/dɔːr/", partOfSpeech: "Noun" },
    { index: "75", english: "Duck", mean: "Con vịt; cúi xuống, né; tránh", pronunciation: "/dʌk/", partOfSpeech: "Noun / Verb" },
    { index: "76", english: "Desk", mean: "Bàn làm việc; bàn học", pronunciation: "/desk/", partOfSpeech: "Noun" },
    { index: "77", english: "Dog", mean: "Con chó; theo dõi, bám theo; đối xử tệ", pronunciation: "/dɔːɡ/", partOfSpeech: "Noun / Verb" },
    { index: "78", english: "Very", mean: "Rất; chính là; đúng là", pronunciation: "/ˈveri/", partOfSpeech: "Adverb / Adjective" },
    { index: "79", english: "Easy", mean: "Dễ; dễ dàng; thoải mái; thư giãn; bình tĩnh", pronunciation: "/ˈiːzi/", partOfSpeech: "Adjective / Adverb" },
    { index: "80", english: "Near", mean: "Gần; gần như; đến gần; gần đây", pronunciation: "/nɪər/", partOfSpeech: "Preposition / Adjective / Adverb / Verb" },
    { index: "81", english: "Window", mean: "Cửa sổ; khoảng thời gian; cửa sổ trên màn hình", pronunciation: "/ˈwɪndəʊ/", partOfSpeech: "Noun" },
    { index: "82", english: "Self", mean: "Bản thân; chính mình; cái tôi", pronunciation: "/self/", partOfSpeech: "Noun" },
    { index: "83", english: "Check", mean: "Kiểm tra; kiểm soát; đánh dấu ✓; hóa đơn; séc; kiểm tra lại", pronunciation: "/tʃek/", partOfSpeech: "Verb / Noun" },
    { index: "84", english: "Cross", mean: "Băng qua; đi ngang qua; vượt qua; bắt chéo; dấu thập; chữ thập; khó chịu; lai", pronunciation: "/krɒs/", partOfSpeech: "Verb / Noun / Adjective" },
    { index: "85", english: "Super", mean: "Siêu; tuyệt vời; rất tốt; người giám sát; siêu thị (viết tắt)", pronunciation: "/ˈsuːpər/", partOfSpeech: "Adjective / Adverb / Noun" },
    { index: "86", english: "At", mean: "Ở; tại; vào (thời điểm); với; trong (một hoạt động/trạng thái)", pronunciation: "/æt/", partOfSpeech: "Preposition" },
    { index: "87", english: "Fish", mean: "Cá; con cá; câu cá", pronunciation: "/fɪʃ/", partOfSpeech: "Noun / Verb" },
    { index: "88", english: "Chips", mean: "Khoai tây chiên; khoai lát chiên; vi mạch, chip điện tử", pronunciation: "/tʃɪps/", partOfSpeech: "Noun" },
    { index: "89", english: "Shop", mean: "Cửa hàng; cửa hiệu; mua sắm; mua", pronunciation: "/ʃɒp/", partOfSpeech: "Noun / Verb" },
    { index: "90", english: "Chicken", mean: "Con gà; thịt gà; người nhát gan", pronunciation: "/ˈtʃɪkɪn/", partOfSpeech: "Noun / Adjective" },
    { index: "91", english: "Milk", mean: "Sữa; vắt sữa; khai thác, tận dụng", pronunciation: "/mɪlk/", partOfSpeech: "Noun / Verb" },
    { index: "92", english: "Like", mean: "Thích; giống như; như là; ví dụ như; kiểu, dạng; sự thích thú", pronunciation: "/laɪk/", partOfSpeech: "Verb / Preposition / Adjective / Noun / Conjunction" },
    { index: "93", english: "Class", mean: "Lớp học; lớp; tiết học; tầng lớp; loại, hạng; đẳng cấp; phân loại", pronunciation: "/klɑːs/", partOfSpeech: "Noun / Verb" },
    { index: "94", english: "Classroom", mean: "Phòng học; lớp học", pronunciation: "/ˈklɑːsruːm/", partOfSpeech: "Noun" },
    { index: "95", english: "Red", mean: "Màu đỏ; đỏ; tức giận; màu đỏ (trong chính trị/chủ nghĩa cộng sản)", pronunciation: "/red/", partOfSpeech: "Noun / Adjective" },
    { index: "96", english: "Pen", mean: "Bút; chuồng, khu quây nhốt động vật; viết bằng bút", pronunciation: "/pen/", partOfSpeech: "Noun / Verb" },
    { index: "97", english: "Pencil", mean: "Bút chì; viết bằng bút chì", pronunciation: "/ˈpensəl/", partOfSpeech: "Noun / Verb" },
    { index: "98", english: "Bell", mean: "Chuông; tiếng chuông; chuông điện thoại; rung chuông", pronunciation: "/bel/", partOfSpeech: "Noun / Verb" },
    { index: "99", english: "How", mean: "Như thế nào; bằng cách nào; bao nhiêu; đến mức nào; thế nào mà; rất, biết bao", pronunciation: "/haʊ/", partOfSpeech: "Adverb / Conjunction" },
    { index: "100", english: "Many", mean: "Nhiều; nhiều người/nhiều thứ", pronunciation: "/ˈmeni/", partOfSpeech: "Determiner / Pronoun / Adjective" },
    { index: "101", english: "People", mean: "Mọi người; người dân; người; dân tộc, cộng đồng", pronunciation: "/ˈpiːpəl/", partOfSpeech: "Noun" },
    { index: "102", english: "He", mean: "Anh ấy; ông ấy; cậu ấy", pronunciation: "/hiː/", partOfSpeech: "Pronoun" },
    { index: "103", english: "She", mean: "Cô ấy; bà ấy; chị ấy", pronunciation: "/ʃiː/", partOfSpeech: "Pronoun" },
    { index: "104", english: "Her", mean: "Cô ấy; bà ấy; chị ấy; của cô ấy, của bà ấy, của chị ấy", pronunciation: "/hɜːr/", partOfSpeech: "Pronoun / Determiner" },
    { index: "105", english: "Him", mean: "Anh ấy; ông ấy; cậu ấy (tân ngữ)", pronunciation: "/hɪm/", partOfSpeech: "Pronoun" },
    { index: "106", english: "It", mean: "Nó; điều đó; việc đó; con vật/đồ vật đó", pronunciation: "/ɪt/", partOfSpeech: "Pronoun" },
    { index: "107", english: "Have", mean: "Có; sở hữu; ăn/uống; trải qua; mắc (bệnh); tổ chức; nhận; phải, cần; khiến/nhờ ai làm gì", pronunciation: "/hæv/", partOfSpeech: "Verb" },

];