/*******************************
 * 1) DỮ LIỆU TỪ VỰNG (ví dụ)
 * Thay/ví dụ bằng 1000 từ của bạn.
 *******************************/
// noun
// pronoun
// verb
// adjective
// adverb
// preposition
// conjunction
// interjection
const vocabularyList = [
    //    // { index: "", english: "", mean: "", pronunciation: "", partOfSpeech: "" },
    { index: "1", english: "tea", mean: "trà", pronunciation: "UK: /tiː/ | US: /tiː/", partOfSpeech: "noun" },
    { index: "2", english: "coffee", mean: "cà phê", pronunciation: "UK: /ˈkɒfi/ | US: /ˈkɔːfi/", partOfSpeech: "noun" },
    { index: "3", english: "welcome", mean: "chào mừng", pronunciation: "UK: /ˈwelkəm/ | US: /ˈwelkəm/", partOfSpeech: "verb, adjective, interjection" },
    { index: "4", english: "please", mean: "vui lòng, làm ơn", pronunciation: "UK: /pliːz/ | US: /pliːz/", partOfSpeech: "interjection, verb" },
    { index: "5", english: "or", mean: "hoặc", pronunciation: "UK: /ɔː/ | US: /ɔːr/", partOfSpeech: "conjunction" },
    { index: "6", english: "sugar", mean: "đường", pronunciation: "UK: /ˈʃʊɡə/ | US: /ˈʃʊɡər/", partOfSpeech: "noun" },
    { index: "7", english: "milk", mean: "sữa", pronunciation: "UK: /mɪlk/ | US: /mɪlk/", partOfSpeech: "noun" },
    { index: "8", english: "with", mean: "với", pronunciation: "UK: /wɪð/ | US: /wɪð/", partOfSpeech: "preposition" },
    { index: "9", english: "water", mean: "nước", pronunciation: "UK: /ˈwɔːtə/ | US: /ˈwɔːtər/", partOfSpeech: "noun" },
    { index: "10", english: "goodbye", mean: "tạm biệt", pronunciation: "UK: /ˌɡʊdˈbaɪ/ | US: /ˌɡʊdˈbaɪ/", partOfSpeech: "interjection, noun" },
    { index: "11", english: "and", mean: "và", pronunciation: "UK: /ænd/ | US: /ænd/", partOfSpeech: "conjunction" },
    { index: "12", english: "thank you", mean: "cảm ơn", pronunciation: "UK: /ˈθæŋk juː/ | US: /ˈθæŋk juː/", partOfSpeech: "interjection" },
    { index: "13", english: "Ball", mean: "Quả bóng", pronunciation: "/bɔːl/", partOfSpeech: "Noun" },
    { index: "14", english: "Bike", mean: "Xe đạp", pronunciation: "/baɪk/", partOfSpeech: "Noun" },
    { index: "15", english: "Book", mean: "Sách", pronunciation: "/bʊk/", partOfSpeech: "Noun" },
    { index: "16", english: "School", mean: "Trường học", pronunciation: "/skuːl/", partOfSpeech: "Noun" },
    { index: "17", english: "Play", mean: "Chơi", pronunciation: "/pleɪ/", partOfSpeech: "Verb" },
    { index: "18", english: "Ground", mean: "Mặt đất", pronunciation: "/ɡraʊnd/", partOfSpeech: "Noun" },
    { index: "19", english: "Playground", mean: "Sân chơi", pronunciation: "/ˈpleɪɡraʊnd/", partOfSpeech: "Noun" },
    { index: "20", english: "Listen", mean: "Lắng nghe", pronunciation: "/ˈlɪsən/", partOfSpeech: "Verb" },
    { index: "21", english: "Repeat", mean: "Lặp lại", pronunciation: "/rɪˈpiːt/", partOfSpeech: "Verb" },
    { index: "22", english: "In", mean: "Trong", pronunciation: "/ɪn/", partOfSpeech: "Preposition" },
    { index: "23", english: "Point", mean: "Điểm; chỉ vào", pronunciation: "/pɔɪnt/", partOfSpeech: "Noun / Verb" },
    { index: "24", english: "Say", mean: "Nói", pronunciation: "/seɪ/", partOfSpeech: "Verb" },
    { index: "25", english: "Lesson", mean: "Bài học", pronunciation: "/ˈlesən/", partOfSpeech: "Noun" },
    { index: "26", english: "Unit", mean: "Đơn vị; bài học", pronunciation: "/ˈjuːnɪt/", partOfSpeech: "Noun" },
    { index: "27", english: "Let", mean: "Cho phép; để", pronunciation: "/let/", partOfSpeech: "Verb" },
    { index: "28", english: "Talk", mean: "Nói chuyện", pronunciation: "/tɔːk/", partOfSpeech: "Verb" },
    { index: "29", english: "Sing", mean: "Hát", pronunciation: "/sɪŋ/", partOfSpeech: "Verb" },
    { index: "30", english: "Chant", mean: "Hô; hát theo nhịp, tụng kinh", pronunciation: "/tʃɑːnt/", partOfSpeech: "Verb / Noun" },
    { index: "31", english: "Tick", mean: "Đánh dấu ✓; tích", pronunciation: "/tɪk/", partOfSpeech: "Verb / Noun" },
    { index: "32", english: "Look", mean: "Nhìn", pronunciation: "/lʊk/", partOfSpeech: "Verb" },
    { index: "33", english: "Trace", mean: "Đồ theo; lần theo dấu vết, theo dõi", pronunciation: "/treɪs/", partOfSpeech: "Verb / Noun" },
    { index: "34", english: "Room", mean: "Phòng; không gian", pronunciation: "/ruːm/", partOfSpeech: "Noun" },
    { index: "35", english: "Dining", mean: "Ăn uống; dùng bữa", pronunciation: "/ˈdaɪnɪŋ/", partOfSpeech: "Noun / Adjective" },
    { index: "36", english: "Dining room", mean: "Phòng ăn", pronunciation: "/ˈdaɪnɪŋ ruːm/", partOfSpeech: "Noun" },
    { index: "37", english: "Extra", mean: "Thêm; bổ sung; dư", pronunciation: "/ˈekstrə/", partOfSpeech: "Adjective / Noun" },
    { index: "38", english: "Resource", mean: "Tài nguyên; nguồn lực", pronunciation: "/rɪˈsɔːrs/", partOfSpeech: "Noun" },
    { index: "39", english: "Glossary", mean: "Bảng chú giải; danh mục từ, bảng thuật ngữ", pronunciation: "/ˈɡlɒsəri/", partOfSpeech: "Noun" },
    { index: "40", english: "Cup", mean: "Cốc; tách", pronunciation: "/kʌp/", partOfSpeech: "Noun" },
    { index: "41", english: "Car", mean: "Xe hơi; ô tô", pronunciation: "/kɑːr/", partOfSpeech: "Noun" },
    { index: "42", english: "Cat", mean: "Con mèo", pronunciation: "/kæt/", partOfSpeech: "Noun" },
    { index: "43", english: "Cake", mean: "Bánh ngọt; bánh", pronunciation: "/keɪk/", partOfSpeech: "Noun" },
    { index: "44", english: "Load", mean: "Tải; chất hàng", pronunciation: "/ləʊd/", partOfSpeech: "Verb / Noun" },
    { index: "45", english: "Loading", mean: "Đang tải", pronunciation: "/ˈləʊdɪŋ/", partOfSpeech: "Noun / Adjective" },
    { index: "46", english: "Fun", mean: "Vui vẻ; niềm vui", pronunciation: "/fʌn/", partOfSpeech: "Noun / Adjective" },
    { index: "47", english: "Time", mean: "Thời gian; lần", pronunciation: "/taɪm/", partOfSpeech: "Noun" },
    { index: "48", english: "Find", mean: "Tìm; tìm thấy", pronunciation: "/faɪnd/", partOfSpeech: "Verb" },
    { index: "49", english: "Circle", mean: "Khoanh tròn; hình tròn", pronunciation: "/ˈsɜːrkəl/", partOfSpeech: "Verb / Noun" },
    { index: "50", english: "Then", mean: "Sau đó; rồi", pronunciation: "/ðen/", partOfSpeech: "Adverb" },
    { index: "51", english: "Color", mean: "Màu sắc; tô màu", pronunciation: "/ˈkʌlər/", partOfSpeech: "Noun / Verb" },
    { index: "52", english: "Colour", mean: "Màu sắc; tô màu", pronunciation: "/ˈkʌlər/", partOfSpeech: "Noun / Verb" },
    { index: "53", english: "Activity", mean: "Hoạt động", pronunciation: "/ækˈtɪvəti/", partOfSpeech: "Noun" },
    { index: "54", english: "Level", mean: "Cấp độ; mức độ; tầng", pronunciation: "/ˈlevəl/", partOfSpeech: "Noun / Adjective / Verb" },
    { index: "55", english: "Little", mean: "Nhỏ; ít", pronunciation: "/ˈlɪtəl/", partOfSpeech: "Adjective / Adverb / Determiner" },
    { index: "56", english: "Big", mean: "To; lớn", pronunciation: "/bɪɡ/", partOfSpeech: "Adjective" },
    { index: "57", english: "Show", mean: "Cho xem; trình diễn", pronunciation: "/ʃəʊ/", partOfSpeech: "Verb / Noun" },
    { index: "58", english: "Happy", mean: "Vui vẻ; hạnh phúc", pronunciation: "/ˈhæpi/", partOfSpeech: "Adjective" },
    { index: "59", english: "Street", mean: "Đường phố", pronunciation: "/striːt/", partOfSpeech: "Noun" },
    { index: "60", english: "Market", mean: "Chợ; thị trường", pronunciation: "/ˈmɑːrkɪt/", partOfSpeech: "Noun" },
    { index: "61", english: "Global", mean: "Toàn cầu", pronunciation: "/ˈɡləʊbəl/", partOfSpeech: "Adjective" },
    { index: "62", english: "Success", mean: "Thành công", pronunciation: "/səkˈses/", partOfSpeech: "Noun" },
    { index: "63", english: "Hat", mean: "Mũ; nón", pronunciation: "/hæt/", partOfSpeech: "Noun" },
    { index: "64", english: "Apple", mean: "Quả táo", pronunciation: "/ˈæpəl/", partOfSpeech: "Noun" },
    { index: "65", english: "Can", mean: "Có thể; có khả năng; được phép; lon; hộp; đóng hộp", pronunciation: "/kæn/", partOfSpeech: "Modal Verb / Noun / Verb" },
    { index: "66", english: "Bag", mean: "Túi; cặp", pronunciation: "/bæɡ/", partOfSpeech: "Noun" },
    { index: "67", english: "On", mean: "Trên; ở trên", pronunciation: "/ɒn/", partOfSpeech: "Preposition / Adverb" },
    { index: "68", english: "There", mean: "Ở đó; kia", pronunciation: "/ðer/", partOfSpeech: "Adverb" },
    { index: "69", english: "This", mean: "Này; cái này", pronunciation: "/ðɪs/", partOfSpeech: "Determiner / Pronoun" },
    { index: "70", english: "Those", mean: "Những cái đó; những người đó", pronunciation: "/ðəʊz/", partOfSpeech: "Determiner / Pronoun" },
    { index: "71", english: "Orange", mean: "Quả cam; màu cam", pronunciation: "/ˈɒrɪndʒ/", partOfSpeech: "Noun / Adjective" },
    { index: "72", english: "Bed", mean: "Giường; luống (cây); đáy (sông, biển); lớp, tầng", pronunciation: "/bed/", partOfSpeech: "Noun / Verb" },
    { index: "73", english: "Bedroom", mean: "Phòng ngủ", pronunciation: "/ˈbedruːm/", partOfSpeech: "Noun" },
    { index: "74", english: "Door", mean: "Cửa; lối vào; cánh cửa", pronunciation: "/dɔːr/", partOfSpeech: "Noun" },
    { index: "75", english: "Duck", mean: "Con vịt; cúi xuống, né; tránh", pronunciation: "/dʌk/", partOfSpeech: "Noun / Verb" },
    { index: "76", english: "Desk", mean: "Bàn làm việc; bàn học", pronunciation: "/desk/", partOfSpeech: "Noun" },
    { index: "77", english: "Dog", mean: "Con chó; theo dõi, bám theo; đối xử tệ", pronunciation: "/dɔːɡ/", partOfSpeech: "Noun / Verb" },
    { index: "78", english: "Very", mean: "Rất; chính là; đúng là", pronunciation: "/ˈveri/", partOfSpeech: "Adverb / Adjective" },
    { index: "79", english: "Easy", mean: "Dễ; dễ dàng; thoải mái; thư giãn; bình tĩnh", pronunciation: "/ˈiːzi/", partOfSpeech: "Adjective / Adverb" },
    { index: "80", english: "Near", mean: "Gần; gần như; đến gần; gần đây", pronunciation: "/nɪər/", partOfSpeech: "Preposition / Adjective / Adverb / Verb" },
    { index: "81", english: "Window", mean: "Cửa sổ; khoảng thời gian; cửa sổ trên màn hình", pronunciation: "/ˈwɪndəʊ/", partOfSpeech: "Noun" },
    { index: "82", english: "Self", mean: "Bản thân; chính mình; cái tôi", pronunciation: "/self/", partOfSpeech: "Noun" },
    { index: "83", english: "Check", mean: "Kiểm tra; kiểm soát; đánh dấu ✓; hóa đơn; séc; kiểm tra lại", pronunciation: "/tʃek/", partOfSpeech: "Verb / Noun" },
    { index: "84", english: "Cross", mean: "Băng qua; đi ngang qua; vượt qua; bắt chéo; dấu thập; chữ thập; khó chịu; lai", pronunciation: "/krɒs/", partOfSpeech: "Verb / Noun / Adjective" },
    { index: "85", english: "Super", mean: "Siêu; tuyệt vời; rất tốt; người giám sát; siêu thị (viết tắt)", pronunciation: "/ˈsuːpər/", partOfSpeech: "Adjective / Adverb / Noun" },
    { index: "86", english: "At", mean: "Ở; tại; vào (thời điểm); với; trong (một hoạt động/trạng thái)", pronunciation: "/æt/", partOfSpeech: "Preposition" },
    { index: "87", english: "Fish", mean: "Cá; con cá; câu cá", pronunciation: "/fɪʃ/", partOfSpeech: "Noun / Verb" },
    { index: "88", english: "Chips", mean: "Khoai tây chiên; khoai lát chiên; vi mạch, chip điện tử", pronunciation: "/tʃɪps/", partOfSpeech: "Noun" },
    { index: "89", english: "Shop", mean: "Cửa hàng; cửa hiệu; mua sắm; mua", pronunciation: "/ʃɒp/", partOfSpeech: "Noun / Verb" },
    { index: "90", english: "Chicken", mean: "Con gà; thịt gà; người nhát gan", pronunciation: "/ˈtʃɪkɪn/", partOfSpeech: "Noun / Adjective" },
    { index: "91", english: "Milk", mean: "Sữa; vắt sữa; khai thác, tận dụng", pronunciation: "/mɪlk/", partOfSpeech: "Noun / Verb" },
    { index: "92", english: "Like", mean: "Thích; giống như; như là; ví dụ như; kiểu, dạng; sự thích thú", pronunciation: "/laɪk/", partOfSpeech: "Verb / Preposition / Adjective / Noun / Conjunction" },
    { index: "93", english: "Class", mean: "Lớp học; lớp; tiết học; tầng lớp; loại, hạng; đẳng cấp; phân loại", pronunciation: "/klɑːs/", partOfSpeech: "Noun / Verb" },
    { index: "94", english: "Classroom", mean: "Phòng học; lớp học", pronunciation: "/ˈklɑːsruːm/", partOfSpeech: "Noun" },
    { index: "95", english: "Red", mean: "Màu đỏ; đỏ; tức giận; màu đỏ (trong chính trị/chủ nghĩa cộng sản)", pronunciation: "/red/", partOfSpeech: "Noun / Adjective" },
    { index: "96", english: "Pen", mean: "Bút; chuồng, khu quây nhốt động vật; viết bằng bút", pronunciation: "/pen/", partOfSpeech: "Noun / Verb" },
    { index: "97", english: "Pencil", mean: "Bút chì; viết bằng bút chì", pronunciation: "/ˈpensəl/", partOfSpeech: "Noun / Verb" },
    { index: "98", english: "Bell", mean: "Chuông; tiếng chuông; chuông điện thoại; rung chuông", pronunciation: "/bel/", partOfSpeech: "Noun / Verb" },
    { index: "99", english: "How", mean: "Như thế nào; bằng cách nào; bao nhiêu; đến mức nào; thế nào mà; rất, biết bao", pronunciation: "/haʊ/", partOfSpeech: "Adverb / Conjunction" },
    { index: "100", english: "Many", mean: "Nhiều; nhiều người/nhiều thứ", pronunciation: "/ˈmeni/", partOfSpeech: "Determiner / Pronoun / Adjective" },
    { index: "101", english: "People", mean: "Mọi người; người dân; người; dân tộc, cộng đồng", pronunciation: "/ˈpiːpəl/", partOfSpeech: "Noun" },
    { index: "102", english: "He", mean: "Anh ấy; ông ấy; cậu ấy", pronunciation: "/hiː/", partOfSpeech: "Pronoun" },
    { index: "103", english: "She", mean: "Cô ấy; bà ấy; chị ấy", pronunciation: "/ʃiː/", partOfSpeech: "Pronoun" },
    { index: "104", english: "Her", mean: "Cô ấy; bà ấy; chị ấy; của cô ấy, của bà ấy, của chị ấy", pronunciation: "/hɜːr/", partOfSpeech: "Pronoun / Determiner" },
    { index: "105", english: "Him", mean: "Anh ấy; ông ấy; cậu ấy (tân ngữ)", pronunciation: "/hɪm/", partOfSpeech: "Pronoun" },
    { index: "106", english: "It", mean: "Nó; điều đó; việc đó; con vật/đồ vật đó", pronunciation: "/ɪt/", partOfSpeech: "Pronoun" },
    { index: "107", english: "Have", mean: "Có; sở hữu; ăn/uống; trải qua; mắc (bệnh); tổ chức; nhận; phải, cần; khiến/nhờ ai làm gì", pronunciation: "/hæv/", partOfSpeech: "Verb" },
    { index: "108", english: "Match", mean: "Ghép, nối; phù hợp; trận đấu; que diêm; sự tương xứng", pronunciation: "/mætʃ/", partOfSpeech: "Verb / Noun" },
    { index: "109", english: "Write", mean: "Viết; ghi; viết thư; sáng tác; viết ra, ghi lại", pronunciation: "/raɪt/", partOfSpeech: "Verb" },
    { index: "110", english: "Air", mean: "Không khí; bầu không khí; vẻ ngoài, phong thái; phát sóng; thông gió", pronunciation: "/eər/", partOfSpeech: "Noun / Verb" },
    { index: "111", english: "Draw", mean: "Vẽ; kéo; lôi; rút; lấy; thu hút; hòa (trận đấu); rút ra, suy ra", pronunciation: "/drɔː/", partOfSpeech: "Verb / Noun" },
    { index: "112", english: "Idea", mean: "Ý tưởng; ý kiến; quan niệm; ý niệm; suy nghĩ", pronunciation: "/aɪˈdɪə/", partOfSpeech: "Noun" },
    { index: "113", english: "Team", mean: "Đội; nhóm; đội ngũ; hợp tác, phối hợp", pronunciation: "/tiːm/", partOfSpeech: "Noun / Verb" },
    { index: "114", english: "Make", mean: "Làm; tạo ra; chế tạo; khiến; làm cho; kiếm (tiền); chuẩn bị; quyết định; đạt được; trở thành; hiểu, nhận ra", pronunciation: "/meɪk/", partOfSpeech: "Verb / Noun" },
    { index: "115", english: "Sentence", mean: "Câu; câu văn; bản án; tuyên án", pronunciation: "/ˈsentəns/", partOfSpeech: "Noun / Verb" },
    { index: "116", english: "Slap", mean: "Tát; vỗ; đánh nhẹ; cái tát; tiếng bốp; đặt mạnh, đặt phịch", pronunciation: "/slæp/", partOfSpeech: "Verb / Noun / Adverb" },
    { index: "117", english: "Board", mean: "Bảng; tấm ván; hội đồng quản trị; lên (tàu, máy bay); ăn ở, trọ; lên máy bay/tàu", pronunciation: "/bɔːrd/", partOfSpeech: "Noun / Verb" },
    { index: "118", english: "Garden", mean: "Khu vườn; làm vườn; trồng cây", pronunciation: "/ˈɡɑːrdən/", partOfSpeech: "Noun / Verb" },
    { index: "119", english: "Boy", mean: "Cậu bé; con trai; chàng trai", pronunciation: "/bɔɪ/", partOfSpeech: "Noun" },
    { index: "120", english: "Girl", mean: "Cô bé; con gái; cô gái", pronunciation: "/ɡɜːrl/", partOfSpeech: "Noun" },
    { index: "121", english: "Goat", mean: "Con dê; người ngốc, người bị đem ra làm trò cười", pronunciation: "/ɡəʊt/", partOfSpeech: "Noun" },
    { index: "122", english: "Gate", mean: "Cổng; cửa; lối vào; kiểm soát/cấm vào", pronunciation: "/ɡeɪt/", partOfSpeech: "Noun / Verb" },
    { index: "123", english: "Park", mean: "Công viên; bãi đỗ xe; đỗ xe; đặt, để", pronunciation: "/pɑːrk/", partOfSpeech: "Noun / Verb" },
    { index: "124", english: "Head", mean: "Đầu; người đứng đầu; thủ lĩnh; phần đầu; đầu mối; đầu trang; đi về phía; dẫn đầu; chỉ huy", pronunciation: "/hed/", partOfSpeech: "Noun / Verb / Adjective" },
    { index: "125", english: "Hand", mean: "Bàn tay; tay; người giúp việc; kim đồng hồ; người lao động; trao, đưa; giúp đỡ; giao, chuyển", pronunciation: "/hænd/", partOfSpeech: "Noun / Verb" },
    { index: "126", english: "Hair", mean: "Tóc; sợi lông; lông trên cơ thể", pronunciation: "/her/", partOfSpeech: "Noun" },
    { index: "127", english: "Horse", mean: "Con ngựa; cưỡi ngựa; chơi ngựa", pronunciation: "/hɔːrs/", partOfSpeech: "Noun / Verb" },
    { index: "128", english: "Touch", mean: "Chạm; sờ; đụng; cảm ứng; liên lạc; ảnh hưởng; cảm động; cái chạm; sự tiếp xúc; nét, dấu vết", pronunciation: "/tʌtʃ/", partOfSpeech: "Verb / Noun" },
    { index: "129", english: "Your", mean: "Của bạn; của các bạn; của anh/chị; của ông/bà", pronunciation: "/jʊər/", partOfSpeech: "Determiner" },
    { index: "130", english: "Out", mean: "Ra ngoài; ở ngoài; hết; không còn; tắt; công khai; không đúng; bị loại; xuất hiện", pronunciation: "/aʊt/", partOfSpeech: "Adverb / Preposition / Adjective" },
    { index: "131", english: "Look out", mean: "Coi chừng; cẩn thận; đề phòng", pronunciation: "/lʊk aʊt/", partOfSpeech: "Phrasal Verb" },
    { index: "132", english: "Lock", mean: "Khóa; ổ khóa; khóa lại; chải, cuộn (tóc); một mớ, cụm", pronunciation: "/lɒk/", partOfSpeech: "Noun / Verb" },
    { index: "133", english: "Clock", mean: "Đồng hồ; bấm giờ; đo thời gian", pronunciation: "/klɒk/", partOfSpeech: "Noun / Verb" },
    { index: "134", english: "Mop", mean: "Cây lau nhà; lau nhà; lau sạch", pronunciation: "/mɒp/", partOfSpeech: "Noun / Verb" },
    { index: "135", english: "Map", mean: "Bản đồ; lập bản đồ; vẽ bản đồ; biểu thị, mô tả", pronunciation: "/mæp/", partOfSpeech: "Noun / Verb" },
    { index: "136", english: "Pot", mean: "Nồi; chậu; bình; hũ; tiền thưởng; đặt vào nồi; trồng vào chậu", pronunciation: "/pɒt/", partOfSpeech: "Noun / Verb" },
    { index: "137", english: "Zoo", mean: "Sở thú; vườn thú; nơi hỗn loạn, lộn xộn", pronunciation: "/zuː/", partOfSpeech: "Noun" },
    { index: "138", english: "Mango", mean: "Quả xoài; cây xoài", pronunciation: "/ˈmæŋɡəʊ/", partOfSpeech: "Noun" },
    { index: "139", english: "Mouse", mean: "Con chuột; chuột máy tính; di chuyển bằng chuột máy tính", pronunciation: "/maʊs/", partOfSpeech: "Noun / Verb" },
    { index: "140", english: "Monkey", mean: "Con khỉ; bắt chước; trêu chọc, nghịch ngợm", pronunciation: "/ˈmʌŋki/", partOfSpeech: "Noun / Verb" },
    { index: "141", english: "Mother", mean: "Mẹ; mẹ đẻ; người mẹ; làm mẹ; sinh ra, nuôi dưỡng", pronunciation: "/ˈmʌðər/", partOfSpeech: "Noun / Verb" },
    { index: "142", english: "Father", mean: "Cha; bố; người sáng lập, người tạo ra; làm cha; tạo ra, sáng lập", pronunciation: "/ˈfɑːðər/", partOfSpeech: "Noun / Verb" },
    { index: "143", english: "For", mean: "Cho; dành cho; vì; bởi vì; để; trong khoảng (thời gian); đối với; thay cho", pronunciation: "/fɔːr/", partOfSpeech: "Preposition / Conjunction" },
    { index: "144", english: "That", mean: "Đó; kia; rằng; mà; cái đó; người đó; đến mức đó", pronunciation: "/ðæt/", partOfSpeech: "Determiner / Pronoun / Conjunction / Adverb" },
    { index: "145", english: "His", mean: "Của anh ấy; của ông ấy; của cậu ấy", pronunciation: "/hɪz/", partOfSpeech: "Determiner / Pronoun" },
    { index: "146", english: "My", mean: "Của tôi; của mình", pronunciation: "/maɪ/", partOfSpeech: "Determiner" },

];